// Code generated by VDL v0.5.0-alpha.5 (commit 1aaf1f7) using varavelio/vdl-plugin-ts@v0.1.2 (hash 81c1ad39)
// Any changes will be overwritten the next time VDL is run. DO NOT EDIT.
// Learn more: https://github.com/varavelio/vdl

/* eslint-disable */
/* tslint:disable */
// biome-ignore-all lint: Generated by VDL

import {
  EnumValueType,
  LiteralKind,
  PrimitiveType,
  TypeKind,
} from "./enums.js";

/**
 * Annotation metadata preserved in IR.
 *
 * `name` is the annotation identifier without the `@` prefix.
 * `argument`, when present, is fully resolved as a LiteralValue.
 */
export type Annotation = {
  /**
   * Source position of this annotation
   */
  position: Position;
  /**
   * Annotation name without `@`
   */
  name: string;
  /**
   * Optional resolved argument payload
   */
  argument?: LiteralValue;
};

/**
 * Annotation exposes the generated runtime helpers for Annotation.
 */
export const Annotation = {
  /**
   * Parses a JSON string into a validated and hydrated Annotation value.
   */
  parse(json: string): Annotation {
    const input = _vdl.parseJson(json);
    const error = Annotation.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return Annotation.hydrate(input as Annotation);
  },

  /**
   * Performs structural validation for Annotation (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "Annotation"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.position`;
    if (
      !_vdl.hasOwn(record0, "position") ||
      record0["position"] === undefined
    ) {
      return `${fieldPath0_0}: required field is missing`;
    }
    {
      const error = Position.validate(record0["position"], fieldPath0_0);
      if (error !== null) {
        return error;
      }
    }
    const fieldPath0_1 = `${path}.name`;
    if (!_vdl.hasOwn(record0, "name") || record0["name"] === undefined) {
      return `${fieldPath0_1}: required field is missing`;
    }
    if (typeof record0["name"] !== "string") {
      return `${fieldPath0_1}: expected string, got ${_vdl.describeValue(record0["name"])}`;
    }
    const fieldPath0_2 = `${path}.argument`;
    if (_vdl.hasOwn(record0, "argument") && record0["argument"] !== undefined) {
      {
        const error = LiteralValue.validate(record0["argument"], fieldPath0_2);
        if (error !== null) {
          return error;
        }
      }
    }
    return null;
  },

  /**
   * Hydrates a validated Annotation value into its runtime representation.
   */
  hydrate(input: Annotation): Annotation {
    return _vdl.withOptional(
      {
        position: Position.hydrate(input.position),
        name: input.name,
      },
      "argument",
      input.argument === undefined
        ? undefined
        : LiteralValue.hydrate(input.argument),
    );
  },
} as const;

/**
 * Fully resolved constant definition.
 *
 * `value` contains the fully resolved literal payload.
 */
export type ConstantDef = {
  /**
   * Source position of this definition
   */
  position: Position;
  /**
   * Constant name
   */
  name: string;
  /**
   * Optional constant documentation
   */
  doc?: string;
  /**
   * Constant annotations in source order
   */
  annotations: Annotation[];
  /**
   * Fully resolved constant value
   */
  value: LiteralValue;
};

/**
 * ConstantDef exposes the generated runtime helpers for ConstantDef.
 */
export const ConstantDef = {
  /**
   * Parses a JSON string into a validated and hydrated ConstantDef value.
   */
  parse(json: string): ConstantDef {
    const input = _vdl.parseJson(json);
    const error = ConstantDef.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return ConstantDef.hydrate(input as ConstantDef);
  },

  /**
   * Performs structural validation for ConstantDef (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "ConstantDef"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.position`;
    if (
      !_vdl.hasOwn(record0, "position") ||
      record0["position"] === undefined
    ) {
      return `${fieldPath0_0}: required field is missing`;
    }
    {
      const error = Position.validate(record0["position"], fieldPath0_0);
      if (error !== null) {
        return error;
      }
    }
    const fieldPath0_1 = `${path}.name`;
    if (!_vdl.hasOwn(record0, "name") || record0["name"] === undefined) {
      return `${fieldPath0_1}: required field is missing`;
    }
    if (typeof record0["name"] !== "string") {
      return `${fieldPath0_1}: expected string, got ${_vdl.describeValue(record0["name"])}`;
    }
    const fieldPath0_2 = `${path}.doc`;
    if (_vdl.hasOwn(record0, "doc") && record0["doc"] !== undefined) {
      if (typeof record0["doc"] !== "string") {
        return `${fieldPath0_2}: expected string, got ${_vdl.describeValue(record0["doc"])}`;
      }
    }
    const fieldPath0_3 = `${path}.annotations`;
    if (
      !_vdl.hasOwn(record0, "annotations") ||
      record0["annotations"] === undefined
    ) {
      return `${fieldPath0_3}: required field is missing`;
    }
    if (!Array.isArray(record0["annotations"])) {
      return `${fieldPath0_3}: expected array, got ${_vdl.describeValue(record0["annotations"])}`;
    }
    for (let index1 = 0; index1 < record0["annotations"].length; index1 += 1) {
      const itemPath1 = `${fieldPath0_3}[${index1}]`;
      {
        const error = Annotation.validate(
          record0["annotations"][index1],
          itemPath1,
        );
        if (error !== null) {
          return error;
        }
      }
    }
    const fieldPath0_4 = `${path}.value`;
    if (!_vdl.hasOwn(record0, "value") || record0["value"] === undefined) {
      return `${fieldPath0_4}: required field is missing`;
    }
    {
      const error = LiteralValue.validate(record0["value"], fieldPath0_4);
      if (error !== null) {
        return error;
      }
    }
    return null;
  },

  /**
   * Hydrates a validated ConstantDef value into its runtime representation.
   */
  hydrate(input: ConstantDef): ConstantDef {
    return _vdl.withOptional(
      {
        position: Position.hydrate(input.position),
        name: input.name,
        annotations: input.annotations.map((item1) =>
          Annotation.hydrate(item1),
        ),
        value: LiteralValue.hydrate(input.value),
      },
      "doc",
      input.doc === undefined ? undefined : input.doc,
    );
  },
} as const;

/**
 * Flattened enum definition.
 *
 * All enum spreads are already expanded into `members`.
 */
export type EnumDef = {
  /**
   * Source position of this definition
   */
  position: Position;
  /**
   * Enum name
   */
  name: string;
  /**
   * Optional enum documentation
   */
  doc?: string;
  /**
   * Enum annotations in source order
   */
  annotations: Annotation[];
  /**
   * Enum underlying storage kind
   */
  enumType: EnumValueType;
  /**
   * Enum members in source order after spread expansion
   */
  members: EnumMember[];
};

/**
 * EnumDef exposes the generated runtime helpers for EnumDef.
 */
export const EnumDef = {
  /**
   * Parses a JSON string into a validated and hydrated EnumDef value.
   */
  parse(json: string): EnumDef {
    const input = _vdl.parseJson(json);
    const error = EnumDef.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return EnumDef.hydrate(input as EnumDef);
  },

  /**
   * Performs structural validation for EnumDef (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "EnumDef"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.position`;
    if (
      !_vdl.hasOwn(record0, "position") ||
      record0["position"] === undefined
    ) {
      return `${fieldPath0_0}: required field is missing`;
    }
    {
      const error = Position.validate(record0["position"], fieldPath0_0);
      if (error !== null) {
        return error;
      }
    }
    const fieldPath0_1 = `${path}.name`;
    if (!_vdl.hasOwn(record0, "name") || record0["name"] === undefined) {
      return `${fieldPath0_1}: required field is missing`;
    }
    if (typeof record0["name"] !== "string") {
      return `${fieldPath0_1}: expected string, got ${_vdl.describeValue(record0["name"])}`;
    }
    const fieldPath0_2 = `${path}.doc`;
    if (_vdl.hasOwn(record0, "doc") && record0["doc"] !== undefined) {
      if (typeof record0["doc"] !== "string") {
        return `${fieldPath0_2}: expected string, got ${_vdl.describeValue(record0["doc"])}`;
      }
    }
    const fieldPath0_3 = `${path}.annotations`;
    if (
      !_vdl.hasOwn(record0, "annotations") ||
      record0["annotations"] === undefined
    ) {
      return `${fieldPath0_3}: required field is missing`;
    }
    if (!Array.isArray(record0["annotations"])) {
      return `${fieldPath0_3}: expected array, got ${_vdl.describeValue(record0["annotations"])}`;
    }
    for (let index1 = 0; index1 < record0["annotations"].length; index1 += 1) {
      const itemPath1 = `${fieldPath0_3}[${index1}]`;
      {
        const error = Annotation.validate(
          record0["annotations"][index1],
          itemPath1,
        );
        if (error !== null) {
          return error;
        }
      }
    }
    const fieldPath0_4 = `${path}.enumType`;
    if (
      !_vdl.hasOwn(record0, "enumType") ||
      record0["enumType"] === undefined
    ) {
      return `${fieldPath0_4}: required field is missing`;
    }
    {
      const error = EnumValueType.validate(record0["enumType"], fieldPath0_4);
      if (error !== null) {
        return error;
      }
    }
    const fieldPath0_5 = `${path}.members`;
    if (!_vdl.hasOwn(record0, "members") || record0["members"] === undefined) {
      return `${fieldPath0_5}: required field is missing`;
    }
    if (!Array.isArray(record0["members"])) {
      return `${fieldPath0_5}: expected array, got ${_vdl.describeValue(record0["members"])}`;
    }
    for (let index1 = 0; index1 < record0["members"].length; index1 += 1) {
      const itemPath1 = `${fieldPath0_5}[${index1}]`;
      {
        const error = EnumMember.validate(
          record0["members"][index1],
          itemPath1,
        );
        if (error !== null) {
          return error;
        }
      }
    }
    return null;
  },

  /**
   * Hydrates a validated EnumDef value into its runtime representation.
   */
  hydrate(input: EnumDef): EnumDef {
    return _vdl.withOptional(
      {
        position: Position.hydrate(input.position),
        name: input.name,
        annotations: input.annotations.map((item1) =>
          Annotation.hydrate(item1),
        ),
        enumType: EnumValueType.hydrate(input.enumType),
        members: input.members.map((item1) => EnumMember.hydrate(item1)),
      },
      "doc",
      input.doc === undefined ? undefined : input.doc,
    );
  },
} as const;

/**
 * Enum member definition
 */
export type EnumMember = {
  /**
   * Source position of this member
   */
  position: Position;
  /**
   * Member name
   */
  name: string;
  /**
   * Fully resolved member value
   */
  value: LiteralValue;
  /**
   * Optional member documentation
   */
  doc?: string;
  /**
   * Member annotations in source order
   */
  annotations: Annotation[];
};

/**
 * EnumMember exposes the generated runtime helpers for EnumMember.
 */
export const EnumMember = {
  /**
   * Parses a JSON string into a validated and hydrated EnumMember value.
   */
  parse(json: string): EnumMember {
    const input = _vdl.parseJson(json);
    const error = EnumMember.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return EnumMember.hydrate(input as EnumMember);
  },

  /**
   * Performs structural validation for EnumMember (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "EnumMember"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.position`;
    if (
      !_vdl.hasOwn(record0, "position") ||
      record0["position"] === undefined
    ) {
      return `${fieldPath0_0}: required field is missing`;
    }
    {
      const error = Position.validate(record0["position"], fieldPath0_0);
      if (error !== null) {
        return error;
      }
    }
    const fieldPath0_1 = `${path}.name`;
    if (!_vdl.hasOwn(record0, "name") || record0["name"] === undefined) {
      return `${fieldPath0_1}: required field is missing`;
    }
    if (typeof record0["name"] !== "string") {
      return `${fieldPath0_1}: expected string, got ${_vdl.describeValue(record0["name"])}`;
    }
    const fieldPath0_2 = `${path}.value`;
    if (!_vdl.hasOwn(record0, "value") || record0["value"] === undefined) {
      return `${fieldPath0_2}: required field is missing`;
    }
    {
      const error = LiteralValue.validate(record0["value"], fieldPath0_2);
      if (error !== null) {
        return error;
      }
    }
    const fieldPath0_3 = `${path}.doc`;
    if (_vdl.hasOwn(record0, "doc") && record0["doc"] !== undefined) {
      if (typeof record0["doc"] !== "string") {
        return `${fieldPath0_3}: expected string, got ${_vdl.describeValue(record0["doc"])}`;
      }
    }
    const fieldPath0_4 = `${path}.annotations`;
    if (
      !_vdl.hasOwn(record0, "annotations") ||
      record0["annotations"] === undefined
    ) {
      return `${fieldPath0_4}: required field is missing`;
    }
    if (!Array.isArray(record0["annotations"])) {
      return `${fieldPath0_4}: expected array, got ${_vdl.describeValue(record0["annotations"])}`;
    }
    for (let index1 = 0; index1 < record0["annotations"].length; index1 += 1) {
      const itemPath1 = `${fieldPath0_4}[${index1}]`;
      {
        const error = Annotation.validate(
          record0["annotations"][index1],
          itemPath1,
        );
        if (error !== null) {
          return error;
        }
      }
    }
    return null;
  },

  /**
   * Hydrates a validated EnumMember value into its runtime representation.
   */
  hydrate(input: EnumMember): EnumMember {
    return _vdl.withOptional(
      {
        position: Position.hydrate(input.position),
        name: input.name,
        value: LiteralValue.hydrate(input.value),
        annotations: input.annotations.map((item1) =>
          Annotation.hydrate(item1),
        ),
      },
      "doc",
      input.doc === undefined ? undefined : input.doc,
    );
  },
} as const;

/**
 * Flattened object/type field definition
 */
export type Field = {
  /**
   * Source position of this field
   */
  position: Position;
  /**
   * Field name
   */
  name: string;
  /**
   * Optional field documentation
   */
  doc?: string;
  /**
   * True when the field is optional (`?`)
   */
  optional: boolean;
  /**
   * Field annotations in source order
   */
  annotations: Annotation[];
  /**
   * Normalized field type reference
   */
  typeRef: TypeRef;
};

/**
 * Field exposes the generated runtime helpers for Field.
 */
export const Field = {
  /**
   * Parses a JSON string into a validated and hydrated Field value.
   */
  parse(json: string): Field {
    const input = _vdl.parseJson(json);
    const error = Field.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return Field.hydrate(input as Field);
  },

  /**
   * Performs structural validation for Field (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "Field"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.position`;
    if (
      !_vdl.hasOwn(record0, "position") ||
      record0["position"] === undefined
    ) {
      return `${fieldPath0_0}: required field is missing`;
    }
    {
      const error = Position.validate(record0["position"], fieldPath0_0);
      if (error !== null) {
        return error;
      }
    }
    const fieldPath0_1 = `${path}.name`;
    if (!_vdl.hasOwn(record0, "name") || record0["name"] === undefined) {
      return `${fieldPath0_1}: required field is missing`;
    }
    if (typeof record0["name"] !== "string") {
      return `${fieldPath0_1}: expected string, got ${_vdl.describeValue(record0["name"])}`;
    }
    const fieldPath0_2 = `${path}.doc`;
    if (_vdl.hasOwn(record0, "doc") && record0["doc"] !== undefined) {
      if (typeof record0["doc"] !== "string") {
        return `${fieldPath0_2}: expected string, got ${_vdl.describeValue(record0["doc"])}`;
      }
    }
    const fieldPath0_3 = `${path}.optional`;
    if (
      !_vdl.hasOwn(record0, "optional") ||
      record0["optional"] === undefined
    ) {
      return `${fieldPath0_3}: required field is missing`;
    }
    if (typeof record0["optional"] !== "boolean") {
      return `${fieldPath0_3}: expected boolean, got ${_vdl.describeValue(record0["optional"])}`;
    }
    const fieldPath0_4 = `${path}.annotations`;
    if (
      !_vdl.hasOwn(record0, "annotations") ||
      record0["annotations"] === undefined
    ) {
      return `${fieldPath0_4}: required field is missing`;
    }
    if (!Array.isArray(record0["annotations"])) {
      return `${fieldPath0_4}: expected array, got ${_vdl.describeValue(record0["annotations"])}`;
    }
    for (let index1 = 0; index1 < record0["annotations"].length; index1 += 1) {
      const itemPath1 = `${fieldPath0_4}[${index1}]`;
      {
        const error = Annotation.validate(
          record0["annotations"][index1],
          itemPath1,
        );
        if (error !== null) {
          return error;
        }
      }
    }
    const fieldPath0_5 = `${path}.typeRef`;
    if (!_vdl.hasOwn(record0, "typeRef") || record0["typeRef"] === undefined) {
      return `${fieldPath0_5}: required field is missing`;
    }
    {
      const error = TypeRef.validate(record0["typeRef"], fieldPath0_5);
      if (error !== null) {
        return error;
      }
    }
    return null;
  },

  /**
   * Hydrates a validated Field value into its runtime representation.
   */
  hydrate(input: Field): Field {
    return _vdl.withOptional(
      {
        position: Position.hydrate(input.position),
        name: input.name,
        optional: input.optional,
        annotations: input.annotations.map((item1) =>
          Annotation.hydrate(item1),
        ),
        typeRef: TypeRef.hydrate(input.typeRef),
      },
      "doc",
      input.doc === undefined ? undefined : input.doc,
    );
  },
} as const;

/**
 * IrSchema is the generator-facing representation of a VDL program.
 *
 * This model is intentionally "flat" and "resolved":
 *
 * - spreads are already expanded
 * - references are already resolved
 * - collections are in deterministic order
 *
 * A code generator should be able to consume IrSchema directly, without needing
 * to re-run parser or semantic-analysis logic.
 */
export type IrSchema = {
  /**
   * Absolute path to the main file that triggered the compilation
   */
  entryPoint: string;
  /**
   * Constant definitions, sorted by name
   */
  constants: ConstantDef[];
  /**
   * Enum definitions, sorted by name
   */
  enums: EnumDef[];
  /**
   * Type definitions, sorted by name
   */
  types: TypeDef[];
  /**
   * Standalone documentation blocks in source traversal order
   */
  docs: TopLevelDoc[];
};

/**
 * IrSchema exposes the generated runtime helpers for IrSchema.
 */
export const IrSchema = {
  /**
   * Parses a JSON string into a validated and hydrated IrSchema value.
   */
  parse(json: string): IrSchema {
    const input = _vdl.parseJson(json);
    const error = IrSchema.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return IrSchema.hydrate(input as IrSchema);
  },

  /**
   * Performs structural validation for IrSchema (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "IrSchema"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.entryPoint`;
    if (
      !_vdl.hasOwn(record0, "entryPoint") ||
      record0["entryPoint"] === undefined
    ) {
      return `${fieldPath0_0}: required field is missing`;
    }
    if (typeof record0["entryPoint"] !== "string") {
      return `${fieldPath0_0}: expected string, got ${_vdl.describeValue(record0["entryPoint"])}`;
    }
    const fieldPath0_1 = `${path}.constants`;
    if (
      !_vdl.hasOwn(record0, "constants") ||
      record0["constants"] === undefined
    ) {
      return `${fieldPath0_1}: required field is missing`;
    }
    if (!Array.isArray(record0["constants"])) {
      return `${fieldPath0_1}: expected array, got ${_vdl.describeValue(record0["constants"])}`;
    }
    for (let index1 = 0; index1 < record0["constants"].length; index1 += 1) {
      const itemPath1 = `${fieldPath0_1}[${index1}]`;
      {
        const error = ConstantDef.validate(
          record0["constants"][index1],
          itemPath1,
        );
        if (error !== null) {
          return error;
        }
      }
    }
    const fieldPath0_2 = `${path}.enums`;
    if (!_vdl.hasOwn(record0, "enums") || record0["enums"] === undefined) {
      return `${fieldPath0_2}: required field is missing`;
    }
    if (!Array.isArray(record0["enums"])) {
      return `${fieldPath0_2}: expected array, got ${_vdl.describeValue(record0["enums"])}`;
    }
    for (let index1 = 0; index1 < record0["enums"].length; index1 += 1) {
      const itemPath1 = `${fieldPath0_2}[${index1}]`;
      {
        const error = EnumDef.validate(record0["enums"][index1], itemPath1);
        if (error !== null) {
          return error;
        }
      }
    }
    const fieldPath0_3 = `${path}.types`;
    if (!_vdl.hasOwn(record0, "types") || record0["types"] === undefined) {
      return `${fieldPath0_3}: required field is missing`;
    }
    if (!Array.isArray(record0["types"])) {
      return `${fieldPath0_3}: expected array, got ${_vdl.describeValue(record0["types"])}`;
    }
    for (let index1 = 0; index1 < record0["types"].length; index1 += 1) {
      const itemPath1 = `${fieldPath0_3}[${index1}]`;
      {
        const error = TypeDef.validate(record0["types"][index1], itemPath1);
        if (error !== null) {
          return error;
        }
      }
    }
    const fieldPath0_4 = `${path}.docs`;
    if (!_vdl.hasOwn(record0, "docs") || record0["docs"] === undefined) {
      return `${fieldPath0_4}: required field is missing`;
    }
    if (!Array.isArray(record0["docs"])) {
      return `${fieldPath0_4}: expected array, got ${_vdl.describeValue(record0["docs"])}`;
    }
    for (let index1 = 0; index1 < record0["docs"].length; index1 += 1) {
      const itemPath1 = `${fieldPath0_4}[${index1}]`;
      {
        const error = TopLevelDoc.validate(record0["docs"][index1], itemPath1);
        if (error !== null) {
          return error;
        }
      }
    }
    return null;
  },

  /**
   * Hydrates a validated IrSchema value into its runtime representation.
   */
  hydrate(input: IrSchema): IrSchema {
    return {
      entryPoint: input.entryPoint,
      constants: input.constants.map((item1) => ConstantDef.hydrate(item1)),
      enums: input.enums.map((item1) => EnumDef.hydrate(item1)),
      types: input.types.map((item1) => TypeDef.hydrate(item1)),
      docs: input.docs.map((item1) => TopLevelDoc.hydrate(item1)),
    };
  },
} as const;

/**
 * Fully resolved literal value.
 *
 * The selected payload is determined by `kind`:
 *
 * - `string` -> `stringValue`
 * - `int` -> `intValue`
 * - `float` -> `floatValue`
 * - `bool` -> `boolValue`
 * - `object` -> `objectEntries`
 * - `array` -> `arrayItems`
 */
export type LiteralValue = {
  /**
   * Source position of this literal value
   */
  position: Position;
  /**
   * Value category discriminator
   */
  kind: LiteralKind;
  /**
   * Payload for `kind = string`
   */
  stringValue?: string;
  /**
   * Payload for `kind = int`
   */
  intValue?: number;
  /**
   * Payload for `kind = float`
   */
  floatValue?: number;
  /**
   * Payload for `kind = bool`
   */
  boolValue?: boolean;
  /**
   * Payload for `kind = object`
   */
  objectEntries?: ObjectEntry[];
  /**
   * Payload for `kind = array`
   */
  arrayItems?: LiteralValue[];
};

/**
 * LiteralValue exposes the generated runtime helpers for LiteralValue.
 */
export const LiteralValue = {
  /**
   * Parses a JSON string into a validated and hydrated LiteralValue value.
   */
  parse(json: string): LiteralValue {
    const input = _vdl.parseJson(json);
    const error = LiteralValue.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return LiteralValue.hydrate(input as LiteralValue);
  },

  /**
   * Performs structural validation for LiteralValue (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "LiteralValue"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.position`;
    if (
      !_vdl.hasOwn(record0, "position") ||
      record0["position"] === undefined
    ) {
      return `${fieldPath0_0}: required field is missing`;
    }
    {
      const error = Position.validate(record0["position"], fieldPath0_0);
      if (error !== null) {
        return error;
      }
    }
    const fieldPath0_1 = `${path}.kind`;
    if (!_vdl.hasOwn(record0, "kind") || record0["kind"] === undefined) {
      return `${fieldPath0_1}: required field is missing`;
    }
    {
      const error = LiteralKind.validate(record0["kind"], fieldPath0_1);
      if (error !== null) {
        return error;
      }
    }
    const fieldPath0_2 = `${path}.stringValue`;
    if (
      _vdl.hasOwn(record0, "stringValue") &&
      record0["stringValue"] !== undefined
    ) {
      if (typeof record0["stringValue"] !== "string") {
        return `${fieldPath0_2}: expected string, got ${_vdl.describeValue(record0["stringValue"])}`;
      }
    }
    const fieldPath0_3 = `${path}.intValue`;
    if (_vdl.hasOwn(record0, "intValue") && record0["intValue"] !== undefined) {
      if (
        typeof record0["intValue"] !== "number" ||
        !Number.isFinite(record0["intValue"])
      ) {
        return `${fieldPath0_3}: expected number, got ${_vdl.describeValue(record0["intValue"])}`;
      }
    }
    const fieldPath0_4 = `${path}.floatValue`;
    if (
      _vdl.hasOwn(record0, "floatValue") &&
      record0["floatValue"] !== undefined
    ) {
      if (
        typeof record0["floatValue"] !== "number" ||
        !Number.isFinite(record0["floatValue"])
      ) {
        return `${fieldPath0_4}: expected number, got ${_vdl.describeValue(record0["floatValue"])}`;
      }
    }
    const fieldPath0_5 = `${path}.boolValue`;
    if (
      _vdl.hasOwn(record0, "boolValue") &&
      record0["boolValue"] !== undefined
    ) {
      if (typeof record0["boolValue"] !== "boolean") {
        return `${fieldPath0_5}: expected boolean, got ${_vdl.describeValue(record0["boolValue"])}`;
      }
    }
    const fieldPath0_6 = `${path}.objectEntries`;
    if (
      _vdl.hasOwn(record0, "objectEntries") &&
      record0["objectEntries"] !== undefined
    ) {
      if (!Array.isArray(record0["objectEntries"])) {
        return `${fieldPath0_6}: expected array, got ${_vdl.describeValue(record0["objectEntries"])}`;
      }
      for (
        let index1 = 0;
        index1 < record0["objectEntries"].length;
        index1 += 1
      ) {
        const itemPath1 = `${fieldPath0_6}[${index1}]`;
        {
          const error = ObjectEntry.validate(
            record0["objectEntries"][index1],
            itemPath1,
          );
          if (error !== null) {
            return error;
          }
        }
      }
    }
    const fieldPath0_7 = `${path}.arrayItems`;
    if (
      _vdl.hasOwn(record0, "arrayItems") &&
      record0["arrayItems"] !== undefined
    ) {
      if (!Array.isArray(record0["arrayItems"])) {
        return `${fieldPath0_7}: expected array, got ${_vdl.describeValue(record0["arrayItems"])}`;
      }
      for (let index1 = 0; index1 < record0["arrayItems"].length; index1 += 1) {
        const itemPath1 = `${fieldPath0_7}[${index1}]`;
        {
          const error = LiteralValue.validate(
            record0["arrayItems"][index1],
            itemPath1,
          );
          if (error !== null) {
            return error;
          }
        }
      }
    }
    return null;
  },

  /**
   * Hydrates a validated LiteralValue value into its runtime representation.
   */
  hydrate(input: LiteralValue): LiteralValue {
    return _vdl.withOptional(
      _vdl.withOptional(
        _vdl.withOptional(
          _vdl.withOptional(
            _vdl.withOptional(
              _vdl.withOptional(
                {
                  position: Position.hydrate(input.position),
                  kind: LiteralKind.hydrate(input.kind),
                },
                "stringValue",
                input.stringValue === undefined ? undefined : input.stringValue,
              ),
              "intValue",
              input.intValue === undefined ? undefined : input.intValue,
            ),
            "floatValue",
            input.floatValue === undefined ? undefined : input.floatValue,
          ),
          "boolValue",
          input.boolValue === undefined ? undefined : input.boolValue,
        ),
        "objectEntries",
        input.objectEntries === undefined
          ? undefined
          : input.objectEntries.map((item1) => ObjectEntry.hydrate(item1)),
      ),
      "arrayItems",
      input.arrayItems === undefined
        ? undefined
        : input.arrayItems.map((item1) => LiteralValue.hydrate(item1)),
    );
  },
} as const;

/**
 * Key/value pair inside an object LiteralValue payload
 */
export type ObjectEntry = {
  /**
   * Source position of this key-value pair
   */
  position: Position;
  /**
   * Object key
   */
  key: string;
  /**
   * Fully resolved value for this key
   */
  value: LiteralValue;
};

/**
 * ObjectEntry exposes the generated runtime helpers for ObjectEntry.
 */
export const ObjectEntry = {
  /**
   * Parses a JSON string into a validated and hydrated ObjectEntry value.
   */
  parse(json: string): ObjectEntry {
    const input = _vdl.parseJson(json);
    const error = ObjectEntry.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return ObjectEntry.hydrate(input as ObjectEntry);
  },

  /**
   * Performs structural validation for ObjectEntry (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "ObjectEntry"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.position`;
    if (
      !_vdl.hasOwn(record0, "position") ||
      record0["position"] === undefined
    ) {
      return `${fieldPath0_0}: required field is missing`;
    }
    {
      const error = Position.validate(record0["position"], fieldPath0_0);
      if (error !== null) {
        return error;
      }
    }
    const fieldPath0_1 = `${path}.key`;
    if (!_vdl.hasOwn(record0, "key") || record0["key"] === undefined) {
      return `${fieldPath0_1}: required field is missing`;
    }
    if (typeof record0["key"] !== "string") {
      return `${fieldPath0_1}: expected string, got ${_vdl.describeValue(record0["key"])}`;
    }
    const fieldPath0_2 = `${path}.value`;
    if (!_vdl.hasOwn(record0, "value") || record0["value"] === undefined) {
      return `${fieldPath0_2}: required field is missing`;
    }
    {
      const error = LiteralValue.validate(record0["value"], fieldPath0_2);
      if (error !== null) {
        return error;
      }
    }
    return null;
  },

  /**
   * Hydrates a validated ObjectEntry value into its runtime representation.
   */
  hydrate(input: ObjectEntry): ObjectEntry {
    return {
      position: Position.hydrate(input.position),
      key: input.key,
      value: LiteralValue.hydrate(input.value),
    };
  },
} as const;

/**
 * PluginInput represents the data payload sent to a plugin.
 *
 * The plugin receives this as a single argument containing the complete
 * Intermediate Representation of the VDL schema along with any user-defined
 * configuration options from `vdl.config.vdl`.
 */
export type PluginInput = {
  /**
   * The VDL binary version (without v prefix, e.g. 1.0.0)
   */
  version: string;
  /**
   * The complete VDL Intermediate Representation.
   *
   * Contains all types, enums, constants, and documentation from the compiled
   * schema, fully resolved and ready for code generation.
   */
  ir: IrSchema;
  /**
   * Arbitrary key-value options passed from the `vdl.config.vdl` plugin configuration.
   *
   * These allow users to customize plugin behavior without modifying the plugin
   * itself. Common use cases include specifying target frameworks, API versions,
   * naming conventions, or feature flags.
   */
  options: Record<string, string>;
};

/**
 * PluginInput exposes the generated runtime helpers for PluginInput.
 */
export const PluginInput = {
  /**
   * Parses a JSON string into a validated and hydrated PluginInput value.
   */
  parse(json: string): PluginInput {
    const input = _vdl.parseJson(json);
    const error = PluginInput.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return PluginInput.hydrate(input as PluginInput);
  },

  /**
   * Performs structural validation for PluginInput (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "PluginInput"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.version`;
    if (!_vdl.hasOwn(record0, "version") || record0["version"] === undefined) {
      return `${fieldPath0_0}: required field is missing`;
    }
    if (typeof record0["version"] !== "string") {
      return `${fieldPath0_0}: expected string, got ${_vdl.describeValue(record0["version"])}`;
    }
    const fieldPath0_1 = `${path}.ir`;
    if (!_vdl.hasOwn(record0, "ir") || record0["ir"] === undefined) {
      return `${fieldPath0_1}: required field is missing`;
    }
    {
      const error = IrSchema.validate(record0["ir"], fieldPath0_1);
      if (error !== null) {
        return error;
      }
    }
    const fieldPath0_2 = `${path}.options`;
    if (!_vdl.hasOwn(record0, "options") || record0["options"] === undefined) {
      return `${fieldPath0_2}: required field is missing`;
    }
    if (!_vdl.isRecord(record0["options"])) {
      return `${fieldPath0_2}: expected object, got ${_vdl.describeValue(record0["options"])}`;
    }
    for (const entry1 of _vdl.recordEntries(record0["options"])) {
      const key1 = entry1[0];
      const value1 = entry1[1];
      const valuePath1 = `${fieldPath0_2}[${JSON.stringify(key1)}]`;
      if (typeof value1 !== "string") {
        return `${valuePath1}: expected string, got ${_vdl.describeValue(value1)}`;
      }
    }
    return null;
  },

  /**
   * Hydrates a validated PluginInput value into its runtime representation.
   */
  hydrate(input: PluginInput): PluginInput {
    return {
      version: input.version,
      ir: IrSchema.hydrate(input.ir),
      options: _vdl.mapRecord(input.options, (value1) => value1),
    };
  },
} as const;

/**
 * PluginOutput represents the response payload returned by the `plugin` function.
 *
 * After processing the input schema, the plugin outputs this object containing
 * all files to be generated or errors to be displayed to the user.
 *
 * If there are no errors and at least one file is returned, VDL will write each
 * file to the specified path within the output directory. If there are errors,
 * VDL will display them to the user and not write any files.
 */
export type PluginOutput = {
  /**
   * List of virtual files generated by the plugin.
   *
   * Each file specifies a relative path within the output directory and its
   * complete textual content. Paths may include subdirectories which VDL
   * will create automatically.
   *
   * If no files are returned, VDL will not write anything.
   */
  files?: PluginOutputFile[];
  /**
   * List of semantic errors encountered by the plugin.
   *
   * If present, VDL will stop the compilation and display them to the user.
   */
  errors?: PluginOutputError[];
};

/**
 * PluginOutput exposes the generated runtime helpers for PluginOutput.
 */
export const PluginOutput = {
  /**
   * Parses a JSON string into a validated and hydrated PluginOutput value.
   */
  parse(json: string): PluginOutput {
    const input = _vdl.parseJson(json);
    const error = PluginOutput.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return PluginOutput.hydrate(input as PluginOutput);
  },

  /**
   * Performs structural validation for PluginOutput (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "PluginOutput"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.files`;
    if (_vdl.hasOwn(record0, "files") && record0["files"] !== undefined) {
      if (!Array.isArray(record0["files"])) {
        return `${fieldPath0_0}: expected array, got ${_vdl.describeValue(record0["files"])}`;
      }
      for (let index1 = 0; index1 < record0["files"].length; index1 += 1) {
        const itemPath1 = `${fieldPath0_0}[${index1}]`;
        {
          const error = PluginOutputFile.validate(
            record0["files"][index1],
            itemPath1,
          );
          if (error !== null) {
            return error;
          }
        }
      }
    }
    const fieldPath0_1 = `${path}.errors`;
    if (_vdl.hasOwn(record0, "errors") && record0["errors"] !== undefined) {
      if (!Array.isArray(record0["errors"])) {
        return `${fieldPath0_1}: expected array, got ${_vdl.describeValue(record0["errors"])}`;
      }
      for (let index1 = 0; index1 < record0["errors"].length; index1 += 1) {
        const itemPath1 = `${fieldPath0_1}[${index1}]`;
        {
          const error = PluginOutputError.validate(
            record0["errors"][index1],
            itemPath1,
          );
          if (error !== null) {
            return error;
          }
        }
      }
    }
    return null;
  },

  /**
   * Hydrates a validated PluginOutput value into its runtime representation.
   */
  hydrate(input: PluginOutput): PluginOutput {
    return _vdl.withOptional(
      _vdl.withOptional(
        {},
        "files",
        input.files === undefined
          ? undefined
          : input.files.map((item1) => PluginOutputFile.hydrate(item1)),
      ),
      "errors",
      input.errors === undefined
        ? undefined
        : input.errors.map((item1) => PluginOutputError.hydrate(item1)),
    );
  },
} as const;

/**
 * A structured error reported by the plugin.
 */
export type PluginOutputError = {
  /**
   * Human-readable error message explaining what went wrong
   */
  message: string;
  /**
   * Optional source position associated with this error.
   * If provided, VDL will print a beautiful snippet highlighting the exact code.
   * If omitted, the error is treated as a global configuration/plugin error.
   */
  position?: Position;
};

/**
 * PluginOutputError exposes the generated runtime helpers for PluginOutputError.
 */
export const PluginOutputError = {
  /**
   * Parses a JSON string into a validated and hydrated PluginOutputError value.
   */
  parse(json: string): PluginOutputError {
    const input = _vdl.parseJson(json);
    const error = PluginOutputError.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return PluginOutputError.hydrate(input as PluginOutputError);
  },

  /**
   * Performs structural validation for PluginOutputError (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "PluginOutputError"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.message`;
    if (!_vdl.hasOwn(record0, "message") || record0["message"] === undefined) {
      return `${fieldPath0_0}: required field is missing`;
    }
    if (typeof record0["message"] !== "string") {
      return `${fieldPath0_0}: expected string, got ${_vdl.describeValue(record0["message"])}`;
    }
    const fieldPath0_1 = `${path}.position`;
    if (_vdl.hasOwn(record0, "position") && record0["position"] !== undefined) {
      {
        const error = Position.validate(record0["position"], fieldPath0_1);
        if (error !== null) {
          return error;
        }
      }
    }
    return null;
  },

  /**
   * Hydrates a validated PluginOutputError value into its runtime representation.
   */
  hydrate(input: PluginOutputError): PluginOutputError {
    return _vdl.withOptional(
      {
        message: input.message,
      },
      "position",
      input.position === undefined
        ? undefined
        : Position.hydrate(input.position),
    );
  },
} as const;

/**
 * PluginOutputFile represents a single generated file produced by the plugin.
 *
 * This abstraction allows plugins to generate multiple files from a single
 * invocation, enabling patterns like one-file-per-type or splitting large
 * outputs across multiple modules.
 */
export type PluginOutputFile = {
  /**
   * Relative path from the output directory where this file should be written.
   *
   * May include subdirectory separators (e.g., "src/models/user.py").
   * Forward slashes are normalized to the appropriate separator for the
   * current operating system.
   */
  path: string;
  /**
   * The complete textual content of the generated file.
   *
   * This should be the final, formatted output ready to be written to disk.
   * VDL writes this content as-is without additional processing.
   */
  content: string;
};

/**
 * PluginOutputFile exposes the generated runtime helpers for PluginOutputFile.
 */
export const PluginOutputFile = {
  /**
   * Parses a JSON string into a validated and hydrated PluginOutputFile value.
   */
  parse(json: string): PluginOutputFile {
    const input = _vdl.parseJson(json);
    const error = PluginOutputFile.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return PluginOutputFile.hydrate(input as PluginOutputFile);
  },

  /**
   * Performs structural validation for PluginOutputFile (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "PluginOutputFile"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.path`;
    if (!_vdl.hasOwn(record0, "path") || record0["path"] === undefined) {
      return `${fieldPath0_0}: required field is missing`;
    }
    if (typeof record0["path"] !== "string") {
      return `${fieldPath0_0}: expected string, got ${_vdl.describeValue(record0["path"])}`;
    }
    const fieldPath0_1 = `${path}.content`;
    if (!_vdl.hasOwn(record0, "content") || record0["content"] === undefined) {
      return `${fieldPath0_1}: required field is missing`;
    }
    if (typeof record0["content"] !== "string") {
      return `${fieldPath0_1}: expected string, got ${_vdl.describeValue(record0["content"])}`;
    }
    return null;
  },

  /**
   * Hydrates a validated PluginOutputFile value into its runtime representation.
   */
  hydrate(input: PluginOutputFile): PluginOutputFile {
    return {
      path: input.path,
      content: input.content,
    };
  },
} as const;

/**
 * It represents a position within a file and is used for error
 * reporting, diagnostics, plugins, and tooling support.
 */
export type Position = {
  /**
   * Absolute file path
   */
  file: string;
  /**
   * Line number (1-indexed)
   */
  line: number;
  /**
   * Column number (1-indexed)
   */
  column: number;
};

/**
 * Position exposes the generated runtime helpers for Position.
 */
export const Position = {
  /**
   * Parses a JSON string into a validated and hydrated Position value.
   */
  parse(json: string): Position {
    const input = _vdl.parseJson(json);
    const error = Position.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return Position.hydrate(input as Position);
  },

  /**
   * Performs structural validation for Position (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "Position"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.file`;
    if (!_vdl.hasOwn(record0, "file") || record0["file"] === undefined) {
      return `${fieldPath0_0}: required field is missing`;
    }
    if (typeof record0["file"] !== "string") {
      return `${fieldPath0_0}: expected string, got ${_vdl.describeValue(record0["file"])}`;
    }
    const fieldPath0_1 = `${path}.line`;
    if (!_vdl.hasOwn(record0, "line") || record0["line"] === undefined) {
      return `${fieldPath0_1}: required field is missing`;
    }
    if (
      typeof record0["line"] !== "number" ||
      !Number.isFinite(record0["line"])
    ) {
      return `${fieldPath0_1}: expected number, got ${_vdl.describeValue(record0["line"])}`;
    }
    const fieldPath0_2 = `${path}.column`;
    if (!_vdl.hasOwn(record0, "column") || record0["column"] === undefined) {
      return `${fieldPath0_2}: required field is missing`;
    }
    if (
      typeof record0["column"] !== "number" ||
      !Number.isFinite(record0["column"])
    ) {
      return `${fieldPath0_2}: expected number, got ${_vdl.describeValue(record0["column"])}`;
    }
    return null;
  },

  /**
   * Hydrates a validated Position value into its runtime representation.
   */
  hydrate(input: Position): Position {
    return {
      file: input.file,
      line: input.line,
      column: input.column,
    };
  },
} as const;

/**
 * Standalone documentation block.
 *
 * Used for top-level docstrings that are not attached to a type/enum/constant.
 */
export type TopLevelDoc = {
  /**
   * Source position of this documentation block
   */
  position: Position;
  /**
   * Resolved documentation content
   */
  content: string;
};

/**
 * TopLevelDoc exposes the generated runtime helpers for TopLevelDoc.
 */
export const TopLevelDoc = {
  /**
   * Parses a JSON string into a validated and hydrated TopLevelDoc value.
   */
  parse(json: string): TopLevelDoc {
    const input = _vdl.parseJson(json);
    const error = TopLevelDoc.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return TopLevelDoc.hydrate(input as TopLevelDoc);
  },

  /**
   * Performs structural validation for TopLevelDoc (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "TopLevelDoc"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.position`;
    if (
      !_vdl.hasOwn(record0, "position") ||
      record0["position"] === undefined
    ) {
      return `${fieldPath0_0}: required field is missing`;
    }
    {
      const error = Position.validate(record0["position"], fieldPath0_0);
      if (error !== null) {
        return error;
      }
    }
    const fieldPath0_1 = `${path}.content`;
    if (!_vdl.hasOwn(record0, "content") || record0["content"] === undefined) {
      return `${fieldPath0_1}: required field is missing`;
    }
    if (typeof record0["content"] !== "string") {
      return `${fieldPath0_1}: expected string, got ${_vdl.describeValue(record0["content"])}`;
    }
    return null;
  },

  /**
   * Hydrates a validated TopLevelDoc value into its runtime representation.
   */
  hydrate(input: TopLevelDoc): TopLevelDoc {
    return {
      position: Position.hydrate(input.position),
      content: input.content,
    };
  },
} as const;

/**
 * Flattened type definition.
 *
 * All spreads are already expanded. The unified `typeRef` describes what this
 * type IS, a primitive, custom reference, map, array, or object with fields.
 */
export type TypeDef = {
  /**
   * Source position of this type definition.
   * Will be zero valued if the type was inferred by the compiler.
   */
  position: Position;
  /**
   * Type name
   */
  name: string;
  /**
   * Optional type documentation
   */
  doc?: string;
  /**
   * Type annotations in source order
   */
  annotations: Annotation[];
  /**
   * Unified type reference describing what this type IS
   */
  typeRef: TypeRef;
};

/**
 * TypeDef exposes the generated runtime helpers for TypeDef.
 */
export const TypeDef = {
  /**
   * Parses a JSON string into a validated and hydrated TypeDef value.
   */
  parse(json: string): TypeDef {
    const input = _vdl.parseJson(json);
    const error = TypeDef.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return TypeDef.hydrate(input as TypeDef);
  },

  /**
   * Performs structural validation for TypeDef (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "TypeDef"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.position`;
    if (
      !_vdl.hasOwn(record0, "position") ||
      record0["position"] === undefined
    ) {
      return `${fieldPath0_0}: required field is missing`;
    }
    {
      const error = Position.validate(record0["position"], fieldPath0_0);
      if (error !== null) {
        return error;
      }
    }
    const fieldPath0_1 = `${path}.name`;
    if (!_vdl.hasOwn(record0, "name") || record0["name"] === undefined) {
      return `${fieldPath0_1}: required field is missing`;
    }
    if (typeof record0["name"] !== "string") {
      return `${fieldPath0_1}: expected string, got ${_vdl.describeValue(record0["name"])}`;
    }
    const fieldPath0_2 = `${path}.doc`;
    if (_vdl.hasOwn(record0, "doc") && record0["doc"] !== undefined) {
      if (typeof record0["doc"] !== "string") {
        return `${fieldPath0_2}: expected string, got ${_vdl.describeValue(record0["doc"])}`;
      }
    }
    const fieldPath0_3 = `${path}.annotations`;
    if (
      !_vdl.hasOwn(record0, "annotations") ||
      record0["annotations"] === undefined
    ) {
      return `${fieldPath0_3}: required field is missing`;
    }
    if (!Array.isArray(record0["annotations"])) {
      return `${fieldPath0_3}: expected array, got ${_vdl.describeValue(record0["annotations"])}`;
    }
    for (let index1 = 0; index1 < record0["annotations"].length; index1 += 1) {
      const itemPath1 = `${fieldPath0_3}[${index1}]`;
      {
        const error = Annotation.validate(
          record0["annotations"][index1],
          itemPath1,
        );
        if (error !== null) {
          return error;
        }
      }
    }
    const fieldPath0_4 = `${path}.typeRef`;
    if (!_vdl.hasOwn(record0, "typeRef") || record0["typeRef"] === undefined) {
      return `${fieldPath0_4}: required field is missing`;
    }
    {
      const error = TypeRef.validate(record0["typeRef"], fieldPath0_4);
      if (error !== null) {
        return error;
      }
    }
    return null;
  },

  /**
   * Hydrates a validated TypeDef value into its runtime representation.
   */
  hydrate(input: TypeDef): TypeDef {
    return _vdl.withOptional(
      {
        position: Position.hydrate(input.position),
        name: input.name,
        annotations: input.annotations.map((item1) =>
          Annotation.hydrate(item1),
        ),
        typeRef: TypeRef.hydrate(input.typeRef),
      },
      "doc",
      input.doc === undefined ? undefined : input.doc,
    );
  },
} as const;

/**
 * Normalized type reference used by fields.
 *
 * `kind` selects which payload fields are meaningful. Generators should inspect
 * `kind` first, then read the related payload fields.
 */
export type TypeRef = {
  /**
   * Type category discriminator
   */
  kind: TypeKind;
  /**
   * Primitive type name when `kind` is `primitive`
   */
  primitiveName?: PrimitiveType;
  /**
   * Referenced type name when `kind` is `type`
   */
  typeName?: string;
  /**
   * Referenced enum name when `kind` is `enum`
   */
  enumName?: string;
  /**
   * Referenced enum underlying kind when `kind` is `enum`
   */
  enumType?: EnumValueType;
  /**
   * Element type when `kind` is `array`
   */
  arrayType?: TypeRef;
  /**
   * Array rank when `kind` is `array` (for example, 2 for `T[][]`)
   */
  arrayDims?: number;
  /**
   * Map value type when `kind` is `map`
   */
  mapType?: TypeRef;
  /**
   * Inline object fields when `kind` is `object`
   */
  objectFields?: Field[];
};

/**
 * TypeRef exposes the generated runtime helpers for TypeRef.
 */
export const TypeRef = {
  /**
   * Parses a JSON string into a validated and hydrated TypeRef value.
   */
  parse(json: string): TypeRef {
    const input = _vdl.parseJson(json);
    const error = TypeRef.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return TypeRef.hydrate(input as TypeRef);
  },

  /**
   * Performs structural validation for TypeRef (required field presence and basic type shape only); it does not enforce business rules.
   */
  validate(input: unknown, path = "TypeRef"): string | null {
    if (!_vdl.isRecord(input)) {
      return `${path}: expected object, got ${_vdl.describeValue(input)}`;
    }
    const record0 = input as Record<string, unknown>;
    const fieldPath0_0 = `${path}.kind`;
    if (!_vdl.hasOwn(record0, "kind") || record0["kind"] === undefined) {
      return `${fieldPath0_0}: required field is missing`;
    }
    {
      const error = TypeKind.validate(record0["kind"], fieldPath0_0);
      if (error !== null) {
        return error;
      }
    }
    const fieldPath0_1 = `${path}.primitiveName`;
    if (
      _vdl.hasOwn(record0, "primitiveName") &&
      record0["primitiveName"] !== undefined
    ) {
      {
        const error = PrimitiveType.validate(
          record0["primitiveName"],
          fieldPath0_1,
        );
        if (error !== null) {
          return error;
        }
      }
    }
    const fieldPath0_2 = `${path}.typeName`;
    if (_vdl.hasOwn(record0, "typeName") && record0["typeName"] !== undefined) {
      if (typeof record0["typeName"] !== "string") {
        return `${fieldPath0_2}: expected string, got ${_vdl.describeValue(record0["typeName"])}`;
      }
    }
    const fieldPath0_3 = `${path}.enumName`;
    if (_vdl.hasOwn(record0, "enumName") && record0["enumName"] !== undefined) {
      if (typeof record0["enumName"] !== "string") {
        return `${fieldPath0_3}: expected string, got ${_vdl.describeValue(record0["enumName"])}`;
      }
    }
    const fieldPath0_4 = `${path}.enumType`;
    if (_vdl.hasOwn(record0, "enumType") && record0["enumType"] !== undefined) {
      {
        const error = EnumValueType.validate(record0["enumType"], fieldPath0_4);
        if (error !== null) {
          return error;
        }
      }
    }
    const fieldPath0_5 = `${path}.arrayType`;
    if (
      _vdl.hasOwn(record0, "arrayType") &&
      record0["arrayType"] !== undefined
    ) {
      {
        const error = TypeRef.validate(record0["arrayType"], fieldPath0_5);
        if (error !== null) {
          return error;
        }
      }
    }
    const fieldPath0_6 = `${path}.arrayDims`;
    if (
      _vdl.hasOwn(record0, "arrayDims") &&
      record0["arrayDims"] !== undefined
    ) {
      if (
        typeof record0["arrayDims"] !== "number" ||
        !Number.isFinite(record0["arrayDims"])
      ) {
        return `${fieldPath0_6}: expected number, got ${_vdl.describeValue(record0["arrayDims"])}`;
      }
    }
    const fieldPath0_7 = `${path}.mapType`;
    if (_vdl.hasOwn(record0, "mapType") && record0["mapType"] !== undefined) {
      {
        const error = TypeRef.validate(record0["mapType"], fieldPath0_7);
        if (error !== null) {
          return error;
        }
      }
    }
    const fieldPath0_8 = `${path}.objectFields`;
    if (
      _vdl.hasOwn(record0, "objectFields") &&
      record0["objectFields"] !== undefined
    ) {
      if (!Array.isArray(record0["objectFields"])) {
        return `${fieldPath0_8}: expected array, got ${_vdl.describeValue(record0["objectFields"])}`;
      }
      for (
        let index1 = 0;
        index1 < record0["objectFields"].length;
        index1 += 1
      ) {
        const itemPath1 = `${fieldPath0_8}[${index1}]`;
        {
          const error = Field.validate(
            record0["objectFields"][index1],
            itemPath1,
          );
          if (error !== null) {
            return error;
          }
        }
      }
    }
    return null;
  },

  /**
   * Hydrates a validated TypeRef value into its runtime representation.
   */
  hydrate(input: TypeRef): TypeRef {
    return _vdl.withOptional(
      _vdl.withOptional(
        _vdl.withOptional(
          _vdl.withOptional(
            _vdl.withOptional(
              _vdl.withOptional(
                _vdl.withOptional(
                  _vdl.withOptional(
                    {
                      kind: TypeKind.hydrate(input.kind),
                    },
                    "primitiveName",
                    input.primitiveName === undefined
                      ? undefined
                      : PrimitiveType.hydrate(input.primitiveName),
                  ),
                  "typeName",
                  input.typeName === undefined ? undefined : input.typeName,
                ),
                "enumName",
                input.enumName === undefined ? undefined : input.enumName,
              ),
              "enumType",
              input.enumType === undefined
                ? undefined
                : EnumValueType.hydrate(input.enumType),
            ),
            "arrayType",
            input.arrayType === undefined
              ? undefined
              : TypeRef.hydrate(input.arrayType),
          ),
          "arrayDims",
          input.arrayDims === undefined ? undefined : input.arrayDims,
        ),
        "mapType",
        input.mapType === undefined
          ? undefined
          : TypeRef.hydrate(input.mapType),
      ),
      "objectFields",
      input.objectFields === undefined
        ? undefined
        : input.objectFields.map((item1) => Field.hydrate(item1)),
    );
  },
} as const;

/**
 * Internal helpers shared by the generated runtime namespaces in this file.
 */
const _vdl = {
  /**
   * Parses JSON text and wraps syntax failures in a stable generated error message.
   */
  parseJson(json: string): unknown {
    try {
      return JSON.parse(json);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      throw new Error(`Invalid JSON input: ${message}`);
    }
  },

  /**
   * Returns own enumerable entries from a record in insertion order.
   */
  recordEntries<TValue>(
    record: Record<string, TValue>,
  ): Array<[string, TValue]> {
    const entries: Array<[string, TValue]> = [];
    for (const key in record) {
      if (Object.prototype.hasOwnProperty.call(record, key)) {
        const value = record[key] as TValue;
        entries.push([key, value]);
      }
    }
    return entries;
  },

  /**
   * Creates a new record by mapping every own enumerable value.
   */
  mapRecord<TInput, TOutput>(
    record: Record<string, TInput>,
    mapValue: (value: TInput) => TOutput,
  ): Record<string, TOutput> {
    const output: Record<string, TOutput> = {};
    for (const key in record) {
      if (Object.prototype.hasOwnProperty.call(record, key)) {
        const value = record[key] as TInput;
        output[key] = mapValue(value);
      }
    }
    return output;
  },

  /**
   * Adds an optional property only when the value is defined.
   */
  withOptional<TRecord extends object, TKey extends string, TValue>(
    record: TRecord,
    key: TKey,
    value: TValue | undefined,
  ): TRecord & Partial<Record<TKey, TValue>> {
    const mutable = record as Record<string, unknown>;
    if (value !== undefined) {
      mutable[key] = value;
    }
    return record as TRecord & Partial<Record<TKey, TValue>>;
  },

  /**
   * Checks whether a value can be validated as a plain object record.
   */
  isRecord(value: unknown): value is Record<string, unknown> {
    return (
      typeof value === "object" &&
      value !== null &&
      !Array.isArray(value) &&
      !(value instanceof Date)
    );
  },

  /**
   * Checks whether a record defines a property directly on the current object.
   */
  hasOwn(record: Record<string, unknown>, key: string): boolean {
    return Object.prototype.hasOwnProperty.call(record, key);
  },

  /**
   * Describes an input value using the categories reported by generated validation errors.
   */
  describeValue(value: unknown): string {
    if (value === null) {
      return "null";
    }
    if (Array.isArray(value)) {
      return "array";
    }
    if (value instanceof Date) {
      return "Date";
    }
    return typeof value;
  },

  /**
   * Checks whether an input can be hydrated into a valid Date instance.
   */
  isValidDateInput(value: unknown): value is string | Date {
    if (value instanceof Date) {
      return !Number.isNaN(value.getTime());
    }
    if (typeof value !== "string") {
      return false;
    }
    return !Number.isNaN(new Date(value).getTime());
  },

  /**
   * Hydrates a string or Date input into a fresh Date instance.
   */
  hydrateDateInput(value: string | Date): Date {
    return value instanceof Date ? new Date(value.getTime()) : new Date(value);
  },
} as const;
