// This file is auto-generated by `scripts/generate-es-toolkit-utils.ts`.
// DO NOT EDIT.

/**
 * Set utility functions re-exported from es-toolkit.
 * Licensed under the MIT License. https://github.com/toss/es-toolkit
 */

import {
  countBy as esToolkit_countBy,
  every as esToolkit_every,
  filter as esToolkit_filter,
  find as esToolkit_find,
  keyBy as esToolkit_keyBy,
  map as esToolkit_map,
  reduce as esToolkit_reduce,
  some as esToolkit_some,
} from "es-toolkit/set";

/**
 * Counts the occurrences of items in a Set based on a transformation function.
 *
 * This function takes a Set and a function that generates a key from each value.
 * It returns a Map with the generated keys and their counts as values.
 * The count is incremented for each element for which the transformation produces the same key.
 *
 * @template T - The type of elements in the Set.
 * @template K - The type of keys produced by the transformation function.
 * @param {Set<T>} set - The Set to count occurrences from.
 * @param {(value: T, value2: T, set: Set<T>) => K} mapper - The function to produce a key for counting.
 * @returns {Map<K, number>} A Map containing the mapped keys and their counts.
 *
 * @example
 * const set = new Set([1, 2, 3, 4, 5]);
 * const result = countBy(set, (value) => value % 2 === 0 ? 'even' : 'odd');
 * // result will be Map(2) { 'odd' => 3, 'even' => 2 }
 *
 * @example
 * const set = new Set(['apple', 'banana', 'cherry']);
 * const result = countBy(set, (value) => value.length);
 * // result will be Map(2) { 5 => 1, 6 => 2 }
 *
 * @see Powered by `es-toolkit` (MIT License): [https://github.com/toss/es-toolkit](https://github.com/toss/es-toolkit)
 */
export const countBy: typeof esToolkit_countBy = esToolkit_countBy;

/**
 * Tests whether all elements in a Set satisfy the provided predicate function.
 *
 * This function iterates through all elements of the Set and checks if the predicate function
 * returns true for every element. It returns true if the predicate is satisfied for all elements,
 * and false otherwise.
 *
 * @template T - The type of elements in the Set.
 * @param {Set<T>} set - The Set to test.
 * @param {(value: T, value2: T, set: Set<T>) => boolean} doesMatch - A predicate function that tests each element.
 * @returns {boolean} true if all elements satisfy the predicate, false otherwise.
 *
 * @example
 * const set = new Set([10, 20, 30]);
 * const result = every(set, (value) => value > 5);
 * // result will be: true
 *
 * const result2 = every(set, (value) => value > 15);
 * // result2 will be: false
 *
 * @see Powered by `es-toolkit` (MIT License): [https://github.com/toss/es-toolkit](https://github.com/toss/es-toolkit)
 */
export const every: typeof esToolkit_every = esToolkit_every;

/**
 * Filters a Set based on a predicate function.
 *
 * This function takes a Set and a predicate function, and returns a new Set containing
 * only the elements for which the predicate function returns true.
 *
 * @template T - The type of elements in the Set.
 * @param {Set<T>} set - The Set to filter.
 * @param {(value: T, value2: T, set: Set<T>) => boolean} callback - A predicate function that tests each element.
 * @returns {Set<T>} A new Set containing only the elements that satisfy the predicate.
 *
 * @example
 * const set = new Set([1, 2, 3, 4, 5]);
 * const result = filter(set, (value) => value > 2);
 * // result will be:
 * // Set(3) { 3, 4, 5 }
 *
 * @see Powered by `es-toolkit` (MIT License): [https://github.com/toss/es-toolkit](https://github.com/toss/es-toolkit)
 */
export const filter: typeof esToolkit_filter = esToolkit_filter;

/**
 * Finds the first element in a Set for which the predicate function returns true.
 *
 * This function iterates through the elements of the Set and returns the first
 * element for which the predicate function returns true. If no element satisfies the predicate,
 * it returns undefined.
 *
 * @template T - The type of elements in the Set.
 * @param {Set<T>} set - The Set to search.
 * @param {(value: T, value2: T, set: Set<T>) => boolean} doesMatch - A predicate function that tests each element.
 * @returns {T | undefined} The first element that satisfies the predicate, or undefined if none found.
 *
 * @example
 * const set = new Set([
 *   { name: 'apple', quantity: 10 },
 *   { name: 'banana', quantity: 5 },
 *   { name: 'grape', quantity: 15 }
 * ]);
 * const result = find(set, (value) => value.quantity > 10);
 * // result will be: { name: 'grape', quantity: 15 }
 *
 * @see Powered by `es-toolkit` (MIT License): [https://github.com/toss/es-toolkit](https://github.com/toss/es-toolkit)
 */
export const find: typeof esToolkit_find = esToolkit_find;

/**
 * Maps each element of a Set based on a provided key-generating function.
 *
 * This function takes a Set and a function that generates a key from each value.
 * It returns a new Map where the keys are generated by the key function and the values are
 * the corresponding values from the original set. If multiple elements produce the same key,
 * the last value encountered will be used.
 *
 * @template T - The type of elements in the Set.
 * @template K - The type of keys to produce in the returned Map.
 * @param {Set<T>} set - The set of elements to be mapped.
 * @param {(value: T, value2: T, set: Set<T>) => K} getKeyFromValue - A function that generates a key from a value.
 * @returns {Map<K, T>} A Map where the generated keys are mapped to each element's value.
 *
 * @example
 * const set = new Set([
 *   { type: 'fruit', name: 'apple' },
 *   { type: 'fruit', name: 'banana' },
 *   { type: 'vegetable', name: 'carrot' }
 * ]);
 * const result = keyBy(set, item => item.type);
 * // result will be:
 * // Map(2) {
 * //   'fruit' => { type: 'fruit', name: 'banana' },
 * //   'vegetable' => { type: 'vegetable', name: 'carrot' }
 * // }
 *
 * @see Powered by `es-toolkit` (MIT License): [https://github.com/toss/es-toolkit](https://github.com/toss/es-toolkit)
 */
export const keyBy: typeof esToolkit_keyBy = esToolkit_keyBy;

/**
 * Creates a new Set with elements transformed by the provided function.
 *
 * This function takes a Set and a function that generates a new value from each element.
 * It returns a new Set where the elements are the result of applying the function to each element.
 *
 * @template T - The type of elements in the input Set.
 * @template U - The type of elements in the output Set.
 * @param {Set<T>} set - The Set to transform.
 * @param {(value: T, value2: T, set: Set<T>) => U} getNewValue - A function that generates a new value from an element.
 * @returns {Set<U>} A new Set with transformed elements.
 *
 * @example
 * const set = new Set([1, 2, 3]);
 * const result = map(set, (value) => value * 2);
 * // result will be:
 * // Set(3) { 2, 4, 6 }
 *
 * @see Powered by `es-toolkit` (MIT License): [https://github.com/toss/es-toolkit](https://github.com/toss/es-toolkit)
 */
export const map: typeof esToolkit_map = esToolkit_map;

/**
 * Reduces a Set to a single value by iterating through its elements and applying a callback function.
 *
 * This function iterates through all elements of the Set and applies the callback function to each element,
 * accumulating the result. If an initial value is provided, it is used as the starting accumulator value.
 * If no initial value is provided and the Set is empty, a TypeError is thrown.
 *
 * @template T - The type of elements in the Set.
 * @template A - The type of the accumulator.
 * @param {Set<T>} set - The Set to reduce.
 * @param {(accumulator: A, value: T, value2: T, set: Set<T>) => A} callback - A function that processes each element and updates the accumulator.
 * @param {A} [initialValue] - The initial value for the accumulator. If not provided, the first element in the Set is used.
 * @returns {A} The final accumulated value.
 * @throws {TypeError} If the Set is empty and no initial value is provided.
 *
 * @example
 * const set = new Set([1, 2, 3]);
 * const result = reduce(set, (acc, value) => acc + value, 0);
 * // result will be: 6
 *
 * @example
 * const set = new Set([10, 20]);
 * const result = reduce(set, (acc, value) => acc + value);
 * // result will be: 30 (starts with first value 10)
 *
 * @see Powered by `es-toolkit` (MIT License): [https://github.com/toss/es-toolkit](https://github.com/toss/es-toolkit)
 */
export const reduce: typeof esToolkit_reduce = esToolkit_reduce;

/**
 * Tests whether at least one element in a Set satisfies the provided predicate function.
 *
 * This function iterates through the elements of the Set and checks if the predicate function
 * returns true for at least one element. It returns true if any element satisfies the predicate,
 * and false otherwise.
 *
 * @template T - The type of elements in the Set.
 * @param {Set<T>} set - The Set to test.
 * @param {(value: T, value2: T, set: Set<T>) => boolean} doesMatch - A predicate function that tests each element.
 * @returns {boolean} true if at least one element satisfies the predicate, false otherwise.
 *
 * @example
 * const set = new Set([1, 2, 3]);
 * const result = some(set, (value) => value > 2);
 * // result will be: true
 *
 * const result2 = some(set, (value) => value > 5);
 * // result2 will be: false
 *
 * @see Powered by `es-toolkit` (MIT License): [https://github.com/toss/es-toolkit](https://github.com/toss/es-toolkit)
 */
export const some: typeof esToolkit_some = esToolkit_some;
