// Code generated by VDL v0.5.0-alpha.5 (commit 1aaf1f7) using varavelio/vdl-plugin-ts@v0.1.2 (hash 81c1ad39)
// Any changes will be overwritten the next time VDL is run. DO NOT EDIT.
// Learn more: https://github.com/varavelio/vdl

/* eslint-disable */
/* tslint:disable */
// biome-ignore-all lint: Generated by VDL

/**
 * Underlying storage kind used by an enum
 */
export type EnumValueType = "string" | "int";

/**
 * EnumValueType exposes the generated enum values and runtime helpers for EnumValueType.
 */
export const EnumValueType = {
  /**
   * Represents the String member of the EnumValueType enum.
   */
  String: "string" as EnumValueType,

  /**
   * Represents the Int member of the EnumValueType enum.
   */
  Int: "int" as EnumValueType,

  /**
   * Returns every declared EnumValueType value in definition order.
   */
  values(): EnumValueType[] {
    return ["string", "int"];
  },

  /**
   * Parses a JSON string into a validated and hydrated EnumValueType value.
   */
  parse(json: string): EnumValueType {
    const input = _vdl.parseJson(json);
    const error = EnumValueType.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return EnumValueType.hydrate(input as EnumValueType);
  },

  /**
   * Performs structural enum validation only (membership in EnumValueType); it does not enforce business rules.
   */
  validate(input: unknown, path = "EnumValueType"): string | null {
    if (!_vdl.arrayIncludes(EnumValueType.values(), input)) {
      return `${path}: invalid value "${String(input)}" for EnumValueType enum`;
    }
    return null;
  },

  /**
   * Hydrates a validated EnumValueType value. Enums return the input unchanged to keep the generated API uniform.
   */
  hydrate(input: EnumValueType): EnumValueType {
    return input;
  },
} as const;

/**
 * Kind discriminator for LiteralValue.
 *
 * LiteralValue is used for fully resolved literal data in:
 *
 * - constant values
 * - annotation arguments
 */
export type LiteralKind =
  | "string"
  | "int"
  | "float"
  | "bool"
  | "object"
  | "array";

/**
 * LiteralKind exposes the generated enum values and runtime helpers for LiteralKind.
 */
export const LiteralKind = {
  /**
   * Represents the String member of the LiteralKind enum.
   */
  String: "string" as LiteralKind,

  /**
   * Represents the Int member of the LiteralKind enum.
   */
  Int: "int" as LiteralKind,

  /**
   * Represents the Float member of the LiteralKind enum.
   */
  Float: "float" as LiteralKind,

  /**
   * Represents the Bool member of the LiteralKind enum.
   */
  Bool: "bool" as LiteralKind,

  /**
   * Represents the Object member of the LiteralKind enum.
   */
  Object: "object" as LiteralKind,

  /**
   * Represents the Array member of the LiteralKind enum.
   */
  Array: "array" as LiteralKind,

  /**
   * Returns every declared LiteralKind value in definition order.
   */
  values(): LiteralKind[] {
    return ["string", "int", "float", "bool", "object", "array"];
  },

  /**
   * Parses a JSON string into a validated and hydrated LiteralKind value.
   */
  parse(json: string): LiteralKind {
    const input = _vdl.parseJson(json);
    const error = LiteralKind.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return LiteralKind.hydrate(input as LiteralKind);
  },

  /**
   * Performs structural enum validation only (membership in LiteralKind); it does not enforce business rules.
   */
  validate(input: unknown, path = "LiteralKind"): string | null {
    if (!_vdl.arrayIncludes(LiteralKind.values(), input)) {
      return `${path}: invalid value "${String(input)}" for LiteralKind enum`;
    }
    return null;
  },

  /**
   * Hydrates a validated LiteralKind value. Enums return the input unchanged to keep the generated API uniform.
   */
  hydrate(input: LiteralKind): LiteralKind {
    return input;
  },
} as const;

/**
 * Primitive scalar type names
 */
export type PrimitiveType = "string" | "int" | "float" | "bool" | "datetime";

/**
 * PrimitiveType exposes the generated enum values and runtime helpers for PrimitiveType.
 */
export const PrimitiveType = {
  /**
   * Represents the String member of the PrimitiveType enum.
   */
  String: "string" as PrimitiveType,

  /**
   * Represents the Int member of the PrimitiveType enum.
   */
  Int: "int" as PrimitiveType,

  /**
   * Represents the Float member of the PrimitiveType enum.
   */
  Float: "float" as PrimitiveType,

  /**
   * Represents the Bool member of the PrimitiveType enum.
   */
  Bool: "bool" as PrimitiveType,

  /**
   * Represents the Datetime member of the PrimitiveType enum.
   */
  Datetime: "datetime" as PrimitiveType,

  /**
   * Returns every declared PrimitiveType value in definition order.
   */
  values(): PrimitiveType[] {
    return ["string", "int", "float", "bool", "datetime"];
  },

  /**
   * Parses a JSON string into a validated and hydrated PrimitiveType value.
   */
  parse(json: string): PrimitiveType {
    const input = _vdl.parseJson(json);
    const error = PrimitiveType.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return PrimitiveType.hydrate(input as PrimitiveType);
  },

  /**
   * Performs structural enum validation only (membership in PrimitiveType); it does not enforce business rules.
   */
  validate(input: unknown, path = "PrimitiveType"): string | null {
    if (!_vdl.arrayIncludes(PrimitiveType.values(), input)) {
      return `${path}: invalid value "${String(input)}" for PrimitiveType enum`;
    }
    return null;
  },

  /**
   * Hydrates a validated PrimitiveType value. Enums return the input unchanged to keep the generated API uniform.
   */
  hydrate(input: PrimitiveType): PrimitiveType {
    return input;
  },
} as const;

/**
 * Kind discriminator for TypeRef
 */
export type TypeKind =
  | "primitive"
  | "type"
  | "enum"
  | "array"
  | "map"
  | "object";

/**
 * TypeKind exposes the generated enum values and runtime helpers for TypeKind.
 */
export const TypeKind = {
  /**
   * Represents the Primitive member of the TypeKind enum.
   */
  Primitive: "primitive" as TypeKind,

  /**
   * Represents the Type member of the TypeKind enum.
   */
  Type: "type" as TypeKind,

  /**
   * Represents the Enum member of the TypeKind enum.
   */
  Enum: "enum" as TypeKind,

  /**
   * Represents the Array member of the TypeKind enum.
   */
  Array: "array" as TypeKind,

  /**
   * Represents the Map member of the TypeKind enum.
   */
  Map: "map" as TypeKind,

  /**
   * Represents the Object member of the TypeKind enum.
   */
  Object: "object" as TypeKind,

  /**
   * Returns every declared TypeKind value in definition order.
   */
  values(): TypeKind[] {
    return ["primitive", "type", "enum", "array", "map", "object"];
  },

  /**
   * Parses a JSON string into a validated and hydrated TypeKind value.
   */
  parse(json: string): TypeKind {
    const input = _vdl.parseJson(json);
    const error = TypeKind.validate(input);
    if (error !== null) {
      throw new Error(error);
    }
    return TypeKind.hydrate(input as TypeKind);
  },

  /**
   * Performs structural enum validation only (membership in TypeKind); it does not enforce business rules.
   */
  validate(input: unknown, path = "TypeKind"): string | null {
    if (!_vdl.arrayIncludes(TypeKind.values(), input)) {
      return `${path}: invalid value "${String(input)}" for TypeKind enum`;
    }
    return null;
  },

  /**
   * Hydrates a validated TypeKind value. Enums return the input unchanged to keep the generated API uniform.
   */
  hydrate(input: TypeKind): TypeKind {
    return input;
  },
} as const;

/**
 * Internal helpers shared by the generated enum namespaces in this file.
 */
const _vdl = {
  /**
   * Parses JSON text and wraps syntax failures in a stable generated error message.
   */
  parseJson(json: string): unknown {
    try {
      return JSON.parse(json);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      throw new Error(`Invalid JSON input: ${message}`);
    }
  },

  /**
   * Checks whether an array contains a value using strict equality.
   */
  arrayIncludes<TValue>(values: TValue[], value: unknown): value is TValue {
    for (let index = 0; index < values.length; index += 1) {
      if (values[index] === value) {
        return true;
      }
    }
    return false;
  },
} as const;
