// This file is auto-generated by `scripts/generate-es-toolkit-utils.mjs`.
// DO NOT EDIT.

/**
 * Map utility functions re-exported from es-toolkit.
 * Licensed under the MIT License. https://github.com/toss/es-toolkit
 */

import {
  every as esToolkit_every,
  filter as esToolkit_filter,
  findKey as esToolkit_findKey,
  findValue as esToolkit_findValue,
  hasValue as esToolkit_hasValue,
  mapKeys as esToolkit_mapKeys,
  mapValues as esToolkit_mapValues,
  reduce as esToolkit_reduce,
  some as esToolkit_some,
} from "es-toolkit/map";

/**
 * Tests whether all entries in a Map satisfy the provided predicate function.
 *
 * This function iterates through all entries of the Map and checks if the predicate function
 * returns true for every entry. It returns true if the predicate is satisfied for all entries,
 * and false otherwise.
 *
 * @template K - The type of keys in the Map.
 * @template V - The type of values in the Map.
 * @param {Map<K, V>} map - The Map to test.
 * @param {(value: V, key: K, map: Map<K, V>) => boolean} doesMatch - A predicate function that tests each entry.
 * @returns {boolean} true if all entries satisfy the predicate, false otherwise.
 *
 * @example
 * const map = new Map([
 *   ['a', 10],
 *   ['b', 20],
 *   ['c', 30]
 * ]);
 * const result = every(map, (value) => value > 5);
 * // result will be: true
 *
 * const result2 = every(map, (value) => value > 15);
 * // result2 will be: false
 *
 * @see Powered by `es-toolkit` (MIT License): https://github.com/toss/es-toolkit
 */
export const every: typeof esToolkit_every = esToolkit_every;

/**
 * Filters a Map based on a predicate function.
 *
 * This function takes a Map and a predicate function, and returns a new Map containing
 * only the entries for which the predicate function returns true.
 *
 * @template K - The type of keys in the Map.
 * @template V - The type of values in the Map.
 * @param {Map<K, V>} map - The Map to filter.
 * @param {(value: V, key: K, map: Map<K, V>) => boolean} callback - A predicate function that tests each entry.
 * @returns {Map<K, V>} A new Map containing only the entries that satisfy the predicate.
 *
 * @example
 * const map = new Map([
 *   ['a', 1],
 *   ['b', 2],
 *   ['c', 3],
 *   ['d', 4]
 * ]);
 * const result = filter(map, (value) => value > 2);
 * // result will be:
 * // Map(2) {
 * //   'c' => 3,
 * //   'd' => 4
 * // }
 *
 * @see Powered by `es-toolkit` (MIT License): https://github.com/toss/es-toolkit
 */
export const filter: typeof esToolkit_filter = esToolkit_filter;

/**
 * Finds the first key in a Map for which the predicate function returns true.
 *
 * This function iterates through the entries of the Map and returns the key of the first
 * entry for which the predicate function returns true. If no entry satisfies the predicate,
 * it returns undefined.
 *
 * @template K - The type of keys in the Map.
 * @template V - The type of values in the Map.
 * @param {Map<K, V>} map - The Map to search.
 * @param {(value: V, key: K, map: Map<K, V>) => boolean} doesMatch - A predicate function that tests each entry.
 * @returns {K | undefined} The key of the first entry that satisfies the predicate, or undefined if none found.
 *
 * @example
 * const map = new Map([
 *   ['apple', { color: 'red', quantity: 10 }],
 *   ['banana', { color: 'yellow', quantity: 5 }],
 *   ['grape', { color: 'purple', quantity: 15 }]
 * ]);
 * const result = findKey(map, (value) => value.quantity > 10);
 * // result will be: 'grape'
 *
 * @see Powered by `es-toolkit` (MIT License): https://github.com/toss/es-toolkit
 */
export const findKey: typeof esToolkit_findKey = esToolkit_findKey;

/**
 * Finds the first value in a Map for which the predicate function returns true.
 *
 * This function iterates through the entries of the Map and returns the value of the first
 * entry for which the predicate function returns true. If no entry satisfies the predicate,
 * it returns undefined.
 *
 * @template K - The type of keys in the Map.
 * @template V - The type of values in the Map.
 * @param {Map<K, V>} map - The Map to search.
 * @param {(value: V, key: K, map: Map<K, V>) => boolean} doesMatch - A predicate function that tests each entry.
 * @returns {V | undefined} The value of the first entry that satisfies the predicate, or undefined if none found.
 *
 * @example
 * const map = new Map([
 *   ['apple', { color: 'red', quantity: 10 }],
 *   ['banana', { color: 'yellow', quantity: 5 }],
 *   ['grape', { color: 'purple', quantity: 15 }]
 * ]);
 * const result = findValue(map, (value) => value.quantity > 10);
 * // result will be: { color: 'purple', quantity: 15 }
 *
 * @see Powered by `es-toolkit` (MIT License): https://github.com/toss/es-toolkit
 */
export const findValue: typeof esToolkit_findValue = esToolkit_findValue;

/**
 * Checks if a Map contains a specific value.
 *
 * This function iterates through all values in the Map and checks if any value
 * is equal to the search element using SameValueZero comparison (similar to
 * Array.prototype.includes). This means that NaN is considered equal to NaN.
 *
 * @template K - The type of keys in the Map.
 * @template V - The type of values in the Map.
 * @param {Map<K, V>} map - The Map to search.
 * @param {V} searchElement - The value to search for.
 * @returns {boolean} true if the Map contains the value, false otherwise.
 *
 * @example
 * const map = new Map([
 *   ['a', 1],
 *   ['b', 2],
 *   ['c', 3]
 * ]);
 * const result = hasValue(map, 2);
 * // result will be: true
 *
 * const result2 = hasValue(map, 5);
 * // result2 will be: false
 *
 * @see Powered by `es-toolkit` (MIT License): https://github.com/toss/es-toolkit
 */
export const hasValue: typeof esToolkit_hasValue = esToolkit_hasValue;

/**
 * Creates a new Map with the same values but with keys transformed by the provided function.
 *
 * This function takes a Map and a function that generates a new key from each value-key pair.
 * It returns a new Map where the keys are the result of applying the function to each entry,
 * while the values remain the same.
 *
 * @template K - The type of keys in the Map.
 * @template V - The type of values in the Map.
 * @param {Map<K, V>} map - The Map to transform.
 * @param {(value: V, key: K, object: Map<K, V>) => K} getNewKey - A function that generates a new key from a value-key pair.
 * @returns {Map<K, V>} A new Map with transformed keys and the same values.
 *
 * @example
 * const map = new Map([
 *   ['a', 1],
 *   ['b', 2],
 *   ['c', 3]
 * ]);
 * const result = mapKeys(map, (value, key) => key.toUpperCase());
 * // result will be:
 * // Map(3) {
 * //   'A' => 1,
 * //   'B' => 2,
 * //   'C' => 3
 * // }
 *
 * @see Powered by `es-toolkit` (MIT License): https://github.com/toss/es-toolkit
 */
export const mapKeys: typeof esToolkit_mapKeys = esToolkit_mapKeys;

/**
 * Creates a new Map with the same keys but with values transformed by the provided function.
 *
 * This function takes a Map and a function that generates a new value from each value-key pair.
 * It returns a new Map where the values are the result of applying the function to each entry,
 * while the keys remain the same.
 *
 * @template K - The type of keys in the Map.
 * @template V - The type of values in the Map.
 * @param {Map<K, V>} map - The Map to transform.
 * @param {(value: V, key: K, object: Map<K, V>) => V} getNewValue - A function that generates a new value from a value-key pair.
 * @returns {Map<K, V>} A new Map with the same keys and transformed values.
 *
 * @example
 * const map = new Map([
 *   ['a', 1],
 *   ['b', 2],
 *   ['c', 3]
 * ]);
 * const result = mapValues(map, (value) => value * 2);
 * // result will be:
 * // Map(3) {
 * //   'a' => 2,
 * //   'b' => 4,
 * //   'c' => 6
 * // }
 *
 * @see Powered by `es-toolkit` (MIT License): https://github.com/toss/es-toolkit
 */
export const mapValues: typeof esToolkit_mapValues = esToolkit_mapValues;

/**
 * Reduces a Map to a single value by iterating through its entries and applying a callback function.
 *
 * This function iterates through all entries of the Map and applies the callback function to each entry,
 * accumulating the result. If an initial value is provided, it is used as the starting accumulator value.
 * If no initial value is provided and the Map is empty, a TypeError is thrown.
 *
 * @template K - The type of keys in the Map.
 * @template V - The type of values in the Map.
 * @param {Map<K, V>} map - The Map to reduce.
 * @param {(accumulator: V, value: V, key: K, map: Map<K, V>) => V} callback - A function that processes each entry and updates the accumulator.
 * @param {V} [initialValue] - The initial value for the accumulator. If not provided, the first value in the Map is used.
 * @returns {V} The final accumulated value.
 * @throws {TypeError} If the Map is empty and no initial value is provided.
 *
 * @example
 * const map = new Map([
 *   ['a', 1],
 *   ['b', 2],
 *   ['c', 3]
 * ]);
 * const result = reduce(map, (acc, value) => acc + value, 0);
 * // result will be: 6
 *
 * @example
 * const map = new Map([
 *   ['a', 10],
 *   ['b', 20]
 * ]);
 * const result = reduce(map, (acc, value) => acc + value);
 * // result will be: 30 (starts with first value 10)
 *
 * @see Powered by `es-toolkit` (MIT License): https://github.com/toss/es-toolkit
 */
export const reduce: typeof esToolkit_reduce = esToolkit_reduce;

/**
 * Tests whether at least one entry in a Map satisfies the provided predicate function.
 *
 * This function iterates through the entries of the Map and checks if the predicate function
 * returns true for at least one entry. It returns true if any entry satisfies the predicate,
 * and false otherwise.
 *
 * @template K - The type of keys in the Map.
 * @template V - The type of values in the Map.
 * @param {Map<K, V>} map - The Map to test.
 * @param {(value: V, key: K, map: Map<K, V>) => boolean} doesMatch - A predicate function that tests each entry.
 * @returns {boolean} true if at least one entry satisfies the predicate, false otherwise.
 *
 * @example
 * const map = new Map([
 *   ['a', 1],
 *   ['b', 2],
 *   ['c', 3]
 * ]);
 * const result = some(map, (value) => value > 2);
 * // result will be: true
 *
 * const result2 = some(map, (value) => value > 5);
 * // result2 will be: false
 *
 * @see Powered by `es-toolkit` (MIT License): https://github.com/toss/es-toolkit
 */
export const some: typeof esToolkit_some = esToolkit_some;
