// This file is auto-generated by `scripts/generate-es-toolkit-utils.mjs`.
// DO NOT EDIT.

/**
 * Small synchronous miscellaneous helpers re-exported from es-toolkit.
 * Licensed under the MIT License. https://github.com/toss/es-toolkit
 */

import {
  assert as esToolkit_assert,
  attempt as esToolkit_attempt,
  invariant as esToolkit_invariant,
} from "es-toolkit/util";

/**
 * Asserts that a given condition is true. If the condition is false, an error is thrown with the provided message.
 *
 * @param {unknown} condition - The condition to evaluate.
 * @param {string} message - The error message to throw if the condition is false.
 * @returns {void} Returns void if the condition is true.
 * @throws {Error} Throws an error if the condition is false.
 *
 * @example
 * // This call will succeed without any errors
 * invariant(true, 'This should not throw');
 *
 * // This call will fail and throw an error with the message 'This should throw'
 * invariant(false, 'This should throw');
 *
 * @copyright Provided by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const assert: typeof esToolkit_assert = esToolkit_assert;

/**
 * Attempt to execute a function and return the result or error.
 * Returns a tuple where:
 * - On success: [null, Result] - First element is null, second is the result
 * - On error: [Error, null] - First element is the caught error, second is null
 *
 * @template {unknown} T - The type of the result of the function.
 * @template {unknown} E - The type of the error that can be thrown by the function.
 * @param {() => T} func - The function to execute.
 * @returns {[null, T] | [E, null]} A tuple containing either [null, result] or [error, null].
 *
 * @example
 * // Successful execution
 * const [error, result] = attempt(() => 42);
 * // [null, 42]
 *
 * // Failed execution
 * const [error, result] = attempt(() => {
 *   throw new Error('Something went wrong');
 * });
 * // [Error, null]
 *
 * // With type parameter
 * const [error, names] = attempt<string[]>(() => ['Alice', 'Bob']);
 * // [null, ['Alice', 'Bob']]
 *
 * @note
 * Important: This function is not suitable for async functions (functions that return a `Promise`).
 * When passing an async function, it will return `[null, Promise<Result>]`, but won't catch any
 * errors if the Promise is rejected later.
 *
 * For handling async functions, use the `attemptAsync` function instead:
 * ```
 * const [error, data] = await attemptAsync(async () => {
 *   const response = await fetch('https://api.example.com/data');
 *   return response.json();
 * });
 * ```
 *
 * @copyright Provided by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const attempt: typeof esToolkit_attempt = esToolkit_attempt;

/**
 * Asserts that a given condition is true. If the condition is false, an error is thrown with the provided message.
 *
 * @param {unknown} condition - The condition to evaluate.
 * @param {string} message - The error message to throw if the condition is false.
 * @returns {void} Returns void if the condition is true.
 * @throws {Error} Throws an error if the condition is false.
 *
 * @example
 * // This call will succeed without any errors
 * invariant(true, 'This should not throw');
 *
 * // This call will fail and throw an error with the message 'This should throw'
 * invariant(false, 'This should throw');
 *
 * @copyright Provided by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const invariant: typeof esToolkit_invariant = esToolkit_invariant;
