// This file is auto-generated by `scripts/generate-es-toolkit-utils.mjs`.
// DO NOT EDIT.

/**
 * Predicate helpers re-exported from es-toolkit.
 * Licensed under the MIT License. https://github.com/toss/es-toolkit
 */

import {
  isBoolean as esToolkit_isBoolean,
  isDate as esToolkit_isDate,
  isEmptyObject as esToolkit_isEmptyObject,
  isEqual as esToolkit_isEqual,
  isError as esToolkit_isError,
  isFunction as esToolkit_isFunction,
  isJSON as esToolkit_isJSON,
  isJSONArray as esToolkit_isJSONArray,
  isJSONObject as esToolkit_isJSONObject,
  isJSONValue as esToolkit_isJSONValue,
  isMap as esToolkit_isMap,
  isNil as esToolkit_isNil,
  isNotNil as esToolkit_isNotNil,
  isNull as esToolkit_isNull,
  isNumber as esToolkit_isNumber,
  isPlainObject as esToolkit_isPlainObject,
  isPrimitive as esToolkit_isPrimitive,
  isRegExp as esToolkit_isRegExp,
  isSet as esToolkit_isSet,
  isString as esToolkit_isString,
  isUndefined as esToolkit_isUndefined,
} from "es-toolkit/predicate";

/**
 * Checks if the given value is boolean.
 *
 * This function tests whether the provided value is strictly `boolean`.
 * It returns `true` if the value is `boolean`, and `false` otherwise.
 *
 * This function can also serve as a type predicate in TypeScript, narrowing the type of the argument to `boolean`.
 *
 * @param {unknown} x - The Value to test if it is boolean.
 * @returns {x is boolean} True if the value is boolean, false otherwise.
 *
 * @example
 *
 * const value1 = true;
 * const value2 = 0;
 * const value3 = 'abc';
 *
 * console.log(isBoolean(value1)); // true
 * console.log(isBoolean(value2)); // false
 * console.log(isBoolean(value3)); // false
 *
 * @copyright Powered by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const isBoolean: typeof esToolkit_isBoolean = esToolkit_isBoolean;

/**
 * Checks if `value` is a Date object.
 *
 * @param {unknown} value The value to check.
 * @returns {value is Date} Returns `true` if `value` is a Date object, `false` otherwise.
 *
 * @example
 * const value1 = new Date();
 * const value2 = '2024-01-01';
 *
 * console.log(isDate(value1)); // true
 * console.log(isDate(value2)); // false
 *
 * @copyright Powered by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const isDate: typeof esToolkit_isDate = esToolkit_isDate;

/**
 * Checks if a value is an empty plain object.
 *
 * @param {unknown} value - The value to check.
 * @returns {value is Record<PropertyKey, never>} - True if the value is an empty plain object, otherwise false.
 *
 * @example
 * isEmptyObject({}); // true
 * isEmptyObject({ a: 1 }); // false
 * isEmptyObject([]); // false
 * isEmptyObject(null); // false
 *
 * @copyright Powered by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const isEmptyObject: typeof esToolkit_isEmptyObject =
  esToolkit_isEmptyObject;

/**
 * Checks if two values are equal, including support for `Date`, `RegExp`, and deep object comparison.
 *
 * @param {unknown} a - The first value to compare.
 * @param {unknown} b - The second value to compare.
 * @returns {boolean} `true` if the values are equal, otherwise `false`.
 *
 * @example
 * isEqual(1, 1); // true
 * isEqual({ a: 1 }, { a: 1 }); // true
 * isEqual(/abc/g, /abc/g); // true
 * isEqual(new Date('2020-01-01'), new Date('2020-01-01')); // true
 * isEqual([1, 2, 3], [1, 2, 3]); // true
 *
 * @copyright Powered by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const isEqual: typeof esToolkit_isEqual = esToolkit_isEqual;

/**
 * Checks if `value` is an Error object.
 *
 * @param {unknown} value The value to check.
 * @returns {value is Error} Returns `true` if `value` is an Error object, `false` otherwise.
 *
 * @example
 * ```typescript
 * console.log(isError(new Error())); // true
 * console.log(isError('Error')); // false
 * console.log(isError({ name: 'Error', message: '' })); // false
 * ```
 *
 * @copyright Powered by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const isError: typeof esToolkit_isError = esToolkit_isError;

/**
 * Checks if `value` is a function.
 *
 * @param {any} value The value to check.
 * @returns {boolean} Returns `true` if `value` is a function, else `false`.
 *
 * @example
 * isFunction(Array.prototype.slice); // true
 * isFunction(async function () {}); // true
 * isFunction(function* () {}); // true
 * isFunction(Proxy); // true
 * isFunction(Int8Array); // true
 *
 * @copyright Powered by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const isFunction: typeof esToolkit_isFunction = esToolkit_isFunction;

/**
 * Checks if a given value is a valid JSON string.
 *
 * A valid JSON string is one that can be successfully parsed using `JSON.parse()`. According to JSON
 * specifications, valid JSON can represent:
 * - Objects (with string keys and valid JSON values)
 * - Arrays (containing valid JSON values)
 * - Strings
 * - Numbers
 * - Booleans
 * - null
 *
 * String values like `"null"`, `"true"`, `"false"`, and numeric strings (e.g., `"42"`) are considered
 * valid JSON and will return true.
 *
 * This function serves as a type guard in TypeScript, narrowing the type of the argument to `string`.
 *
 * @param {unknown} value The value to check.
 * @returns {boolean} Returns `true` if `value` is a valid JSON string, else `false`.
 *
 * @example
 * isJSON('{"name":"John","age":30}'); // true
 * isJSON('[1,2,3]'); // true
 * isJSON('true'); // true
 * isJSON('invalid json'); // false
 * isJSON({ name: 'John' }); // false (not a string)
 * isJSON(null); // false (not a string)
 *
 * @copyright Powered by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const isJSON: typeof esToolkit_isJSON = esToolkit_isJSON;

/**
 * Checks if a given value is a valid JSON value.
 *
 * A valid JSON value can be:
 * - null
 * - a JSON object (an object with string keys and valid JSON values)
 * - a JSON array (an array of valid JSON values)
 * - a string
 * - a number
 * - a boolean
 *
 * @param {unknown} value - The value to check.
 * @returns {boolean} - True if the value is a valid JSON value, otherwise false.
 *
 * @example
 * console.log(isJSONValue(null)); // true
 * console.log(isJSONValue({ key: "value" })); // true
 * console.log(isJSONValue([1, 2, 3])); // true
 * console.log(isJSONValue("Hello")); // true
 * console.log(isJSONValue(42)); // true
 * console.log(isJSONValue(true)); // true
 * console.log(isJSONValue(undefined)); // false
 * console.log(isJSONValue(() => {})); // false
 *
 * @copyright Powered by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const isJSONArray: typeof esToolkit_isJSONArray = esToolkit_isJSONArray;

/**
 * Checks if a given value is a valid JSON value.
 *
 * A valid JSON value can be:
 * - null
 * - a JSON object (an object with string keys and valid JSON values)
 * - a JSON array (an array of valid JSON values)
 * - a string
 * - a number
 * - a boolean
 *
 * @param {unknown} value - The value to check.
 * @returns {boolean} - True if the value is a valid JSON value, otherwise false.
 *
 * @example
 * console.log(isJSONValue(null)); // true
 * console.log(isJSONValue({ key: "value" })); // true
 * console.log(isJSONValue([1, 2, 3])); // true
 * console.log(isJSONValue("Hello")); // true
 * console.log(isJSONValue(42)); // true
 * console.log(isJSONValue(true)); // true
 * console.log(isJSONValue(undefined)); // false
 * console.log(isJSONValue(() => {})); // false
 *
 * @copyright Powered by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const isJSONObject: typeof esToolkit_isJSONObject =
  esToolkit_isJSONObject;

/**
 * Checks if a given value is a valid JSON value.
 *
 * A valid JSON value can be:
 * - null
 * - a JSON object (an object with string keys and valid JSON values)
 * - a JSON array (an array of valid JSON values)
 * - a string
 * - a number
 * - a boolean
 *
 * @param {unknown} value - The value to check.
 * @returns {boolean} - True if the value is a valid JSON value, otherwise false.
 *
 * @example
 * console.log(isJSONValue(null)); // true
 * console.log(isJSONValue({ key: "value" })); // true
 * console.log(isJSONValue([1, 2, 3])); // true
 * console.log(isJSONValue("Hello")); // true
 * console.log(isJSONValue(42)); // true
 * console.log(isJSONValue(true)); // true
 * console.log(isJSONValue(undefined)); // false
 * console.log(isJSONValue(() => {})); // false
 *
 * @copyright Powered by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const isJSONValue: typeof esToolkit_isJSONValue = esToolkit_isJSONValue;

/**
 * Checks if a given value is `Map`.
 *
 * This function can also serve as a type predicate in TypeScript, narrowing the type of the argument to `Map`.
 *
 * @param {unknown} value The value to check if it is a `Map`.
 * @returns {value is Map<any, any>} Returns `true` if `value` is a `Map`, else `false`.
 *
 * @example
 * const value1 = new Map();
 * const value2 = new Set();
 * const value3 = new WeakMap();
 *
 * console.log(isMap(value1)); // true
 * console.log(isMap(value2)); // false
 * console.log(isMap(value3)); // false
 *
 * @copyright Powered by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const isMap: typeof esToolkit_isMap = esToolkit_isMap;

/**
 * Checks if a given value is null or undefined.
 *
 * This function tests whether the provided value is either `null` or `undefined`.
 * It returns `true` if the value is `null` or `undefined`, and `false` otherwise.
 *
 * This function can also serve as a type predicate in TypeScript, narrowing the type of the argument to `null` or `undefined`.
 *
 * @param {unknown} x - The value to test for null or undefined.
 * @returns {boolean} `true` if the value is null or undefined, `false` otherwise.
 *
 * @example
 * const value1 = null;
 * const value2 = undefined;
 * const value3 = 42;
 * const result1 = isNil(value1); // true
 * const result2 = isNil(value2); // true
 * const result3 = isNil(value3); // false
 *
 * @copyright Powered by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const isNil: typeof esToolkit_isNil = esToolkit_isNil;

/**
 * Checks if the given value is not null nor undefined.
 *
 * The main use of this function is to be used with TypeScript as a type predicate.
 *
 * @template T - The type of value.
 * @param {T | null | undefined} x - The value to test if it is not null nor undefined.
 * @returns {x is T} True if the value is not null nor undefined, false otherwise.
 *
 * @example
 * // Here the type of `arr` is (number | undefined)[]
 * const arr = [1, undefined, 3];
 * // Here the type of `result` is number[]
 * const result = arr.filter(isNotNil);
 * // result will be [1, 3]
 *
 * @copyright Powered by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const isNotNil: typeof esToolkit_isNotNil = esToolkit_isNotNil;

/**
 * Checks if the given value is null.
 *
 * This function tests whether the provided value is strictly equal to `null`.
 * It returns `true` if the value is `null`, and `false` otherwise.
 *
 * This function can also serve as a type predicate in TypeScript, narrowing the type of the argument to `null`.
 *
 * @param {unknown} x - The value to test if it is null.
 * @returns {x is null} True if the value is null, false otherwise.
 *
 * @example
 * const value1 = null;
 * const value2 = undefined;
 * const value3 = 42;
 *
 * console.log(isNull(value1)); // true
 * console.log(isNull(value2)); // false
 * console.log(isNull(value3)); // false
 *
 * @copyright Powered by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const isNull: typeof esToolkit_isNull = esToolkit_isNull;

/**
 * Checks if the given value is a number.
 *
 * This function tests whether the provided value is strictly a `number`.
 * It returns `true` if the value is a `number`, and `false` otherwise.
 *
 * This function can also serve as a type predicate in TypeScript, narrowing the type of the argument to `number`.
 *
 * @param {unknown} x - The value to test if it is a number.
 * @returns {x is number} True if the value is a number, false otherwise.
 *
 * @example
 *
 * const value1 = 123;
 * const value2 = 'abc';
 * const value3 = true;
 *
 * console.log(isNumber(value1)); // true
 * console.log(isNumber(value2)); // false
 * console.log(isNumber(value3)); // false
 *
 * @copyright Powered by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const isNumber: typeof esToolkit_isNumber = esToolkit_isNumber;

/**
 * Checks if a given value is a plain object.
 *
 * @param {object} value - The value to check.
 * @returns {value is Record<PropertyKey, any>} - True if the value is a plain object, otherwise false.
 *
 * @example
 * ```typescript
 * // ✅👇 True
 *
 * isPlainObject({ });                       // ✅
 * isPlainObject({ key: 'value' });          // ✅
 * isPlainObject({ key: new Date() });       // ✅
 * isPlainObject(new Object());              // ✅
 * isPlainObject(Object.create(null));       // ✅
 * isPlainObject({ nested: { key: true} });  // ✅
 * isPlainObject(new Proxy({}, {}));         // ✅
 * isPlainObject({ [Symbol('tag')]: 'A' });  // ✅
 *
 * // ✅👇 (cross-realms, node context, workers, ...)
 * const runInNewContext = await import('node:vm').then(
 *     (mod) => mod.runInNewContext
 * );
 * isPlainObject(runInNewContext('({})'));   // ✅
 *
 * // ❌👇 False
 *
 * class Test { };
 * isPlainObject(new Test())           // ❌
 * isPlainObject(10);                  // ❌
 * isPlainObject(null);                // ❌
 * isPlainObject('hello');             // ❌
 * isPlainObject([]);                  // ❌
 * isPlainObject(new Date());          // ❌
 * isPlainObject(new Uint8Array([1])); // ❌
 * isPlainObject(Buffer.from('ABC'));  // ❌
 * isPlainObject(Promise.resolve({})); // ❌
 * isPlainObject(Object.create({}));   // ❌
 * isPlainObject(new (class Cls {}));  // ❌
 * isPlainObject(globalThis);          // ❌,
 * ```
 *
 * @copyright Powered by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const isPlainObject: typeof esToolkit_isPlainObject =
  esToolkit_isPlainObject;

/**
 * Checks whether a value is a JavaScript primitive.
 * JavaScript primitives include null, undefined, strings, numbers, booleans, symbols, and bigints.
 *
 * @param {unknown} value The value to check.
 * @returns {value is
 *     null
 *   | undefined
 *   | string
 *   | number
 *   | boolean
 *   | symbol
 *   | bigint} Returns true if `value` is a primitive, false otherwise.
 *
 * @example
 * isPrimitive(null); // true
 * isPrimitive(undefined); // true
 * isPrimitive('123'); // true
 * isPrimitive(false); // true
 * isPrimitive(true); // true
 * isPrimitive(Symbol('a')); // true
 * isPrimitive(123n); // true
 * isPrimitive({}); // false
 * isPrimitive(new Date()); // false
 * isPrimitive(new Map()); // false
 * isPrimitive(new Set()); // false
 * isPrimitive([1, 2, 3]); // false
 *
 * @copyright Powered by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const isPrimitive: typeof esToolkit_isPrimitive = esToolkit_isPrimitive;

/**
 * Checks if `value` is a RegExp.
 *
 * @param {unknown} value The value to check.
 * @returns {value is RegExp} Returns `true` if `value` is a RegExp, `false` otherwise.
 *
 * @example
 * const value1 = /abc/;
 * const value2 = '/abc/';
 *
 * console.log(isRegExp(value1)); // true
 * console.log(isRegExp(value2)); // false
 *
 * @copyright Powered by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const isRegExp: typeof esToolkit_isRegExp = esToolkit_isRegExp;

/**
 * Checks if a given value is `Set`.
 *
 * This function can also serve as a type predicate in TypeScript, narrowing the type of the argument to `Set`.
 *
 * @param {unknown} value The value to check if it is a `Set`.
 * @returns {value is Set<any>} Returns `true` if `value` is a `Set`, else `false`.
 *
 * @example
 * const value1 = new Set();
 * const value2 = new Map();
 * const value3 = new WeakSet();
 *
 * console.log(isSet(value1)); // true
 * console.log(isSet(value2)); // false
 * console.log(isSet(value3)); // false
 *
 * @copyright Powered by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const isSet: typeof esToolkit_isSet = esToolkit_isSet;

/**
 * Checks if a given value is string.
 *
 * This function can also serve as a type predicate in TypeScript, narrowing the type of the argument to `string`.
 *
 * @param {unknown} value The value to check if it is string.
 * @returns {value is string} Returns `true` if `value` is a string, else `false`.
 *
 * @example
 * const value1 = 'abc';
 * const value2 = 123;
 * const value3 = true;
 *
 * console.log(isString(value1)); // true
 * console.log(isString(value2)); // false
 * console.log(isString(value3)); // false
 *
 * @copyright Powered by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const isString: typeof esToolkit_isString = esToolkit_isString;

/**
 * Checks if the given value is undefined.
 *
 * This function tests whether the provided value is strictly equal to `undefined`.
 * It returns `true` if the value is `undefined`, and `false` otherwise.
 *
 * This function can also serve as a type predicate in TypeScript, narrowing the type of the argument to `undefined`.
 *
 * @param {unknown} x - The value to test if it is undefined.
 * @returns {x is undefined} true if the value is undefined, false otherwise.
 *
 * @example
 * const value1 = undefined;
 * const value2 = null;
 * const value3 = 42;
 *
 * console.log(isUndefined(value1)); // true
 * console.log(isUndefined(value2)); // false
 * console.log(isUndefined(value3)); // false
 *
 * @copyright Powered by [es-toolkit](https://github.com/toss/es-toolkit) (MIT License).
 */
export const isUndefined: typeof esToolkit_isUndefined = esToolkit_isUndefined;
